### ISSUE TITLE
Erros on executing run_huey (>= 1.0.0) with Django 1.9

### ISSUE THREAD

**Issue by psyonara** [coleifer/huey#135]
Hi there,

I'm getting error(s) when using Huey 1.0.0+ with Django (when running run_huey) on a specific setup (will paste errors at the end):
Ubuntu 14.04 LTS
Python 2.7.6
Django 1.9
Redis 2.8.4

However, on another setup the errors don't come up:
Ubuntu 15.10
Python 2.7.9
Django 1.9
Redis 3.0.3

So, on the first setup, using Huey version 1.0.0, I get the following error:
```
Exception in thread Scheduler:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/somari/Revolution/ve/local/lib/python2.7/site-packages/huey/consumer.py", line 293, in _run
    consumer_process.loop()
  File "/home/somari/Revolution/ve/local/lib/python2.7/site-packages/huey/consumer.py", line 167, in loop
    for task in self.huey.read_schedule(now):
  File "/home/somari/Revolution/ve/local/lib/python2.7/site-packages/huey/api.py", line 301, in read_schedule
    for m in self._read_schedule(ts)]
  File "/home/somari/Revolution/ve/local/lib/python2.7/site-packages/huey/api.py", line 165, in inner
    wrap_exception(exc_class)
  File "/home/somari/Revolution/ve/local/lib/python2.7/site-packages/huey/utils.py", line 18, in wrap_exception
    raise new_exc_class('%s: %s' % (exc_class.__name__, exc))
ScheduleReadException: TypeError: __init__() got an unexpected keyword argument 'consumer_options'
```

When using Huey 1.1.0, I get the above error plus the following:
```
Exception in thread Worker-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/somari/Revolution/ve/local/lib/python2.7/site-packages/huey/consumer.py", line 359, in _run
    consumer_process.loop()
  File "/home/somari/Revolution/ve/local/lib/python2.7/site-packages/huey/consumer.py", line 95, in loop
    self.huey.emit_task(EVENT_ERROR_DEQUEUEING, task, error=True)
  File "/home/somari/Revolution/ve/local/lib/python2.7/site-packages/huey/api.py", line 256, in emit_task
    metadata = self._get_task_metadata(task, error)
  File "/home/somari/Revolution/ve/local/lib/python2.7/site-packages/huey/api.py", line 236, in _get_task_metadata
    'id': task.task_id,
AttributeError: 'NoneType' object has no attribute 'task_id'
```

Since my "newer" setup doesn't produce the errors, I presume my Huey settings are fine. So then it must be the version difference of python, redis, or both? Some insight would be appreciated! :-)

**Comment by coleifer** [comment]
Can you share how you're running huey (command, settings, options, etc)?

**Comment by psyonara** [comment]
The Django settings file contains this:
```py
HUEY = RedisHuey('blah')
```

Then we run Huey with:
```sh
python manage.py run_huey
```

Everything else is set to defaults (e.g. Redis).

**Comment by psyonara** [comment]
Never mind, it has been resolved. For some reason (which is beyond me), it had somehow cached the old settings. But a restart of everything solved that.

Sorry for the trouble!
