### ISSUE TITLE
Periodic Tasks Blocking Others

### ISSUE THREAD

**Issue by dmcmulle** [coleifer/huey#143]
Hello.  I am using huey with a redis backend.

I have two functions as such:

```
@task
request_report():
```
and 
```
@periodic_task(crontab(hour='*/4'))
def periodic_task_report():
```

For some reason, whenever task `periodic_task_report` is running, all other tasks are blocked and cannot be executed.  I am using huey with django and it is setup like so:
```
    HUEY = {
        'name': 'my-redis-name',
        'connection': {'host': 'localhost', 'port': 6379},
        'consumer': {'workers': 4, 'worker_type': 'thread'},
        'always_eager': False
    }
```

At first, all request_report jobs were being ignored.  Then, after restarting my server and reconnecting, I was getting the following error:

```
2016-03-15T02:12:46.418462+00:00 app[worker.1]: Exception in thread Worker-2:
2016-03-15T02:12:46.418484+00:00 app[worker.1]: Traceback (most recent call last):
2016-03-15T02:12:46.418485+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/threading.py", line 801, in __bootstrap_inner
2016-03-15T02:12:46.418493+00:00 app[worker.1]:     self.run()
2016-03-15T02:12:46.418501+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/threading.py", line 754, in run
2016-03-15T02:12:46.418509+00:00 app[worker.1]:     self.__target(*self.__args, **self.__kwargs)
2016-03-15T02:12:46.418510+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/huey/consumer.py", line 359, in _run
2016-03-15T02:12:46.418510+00:00 app[worker.1]:     consumer_process.loop()
2016-03-15T02:12:46.418511+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/huey/consumer.py", line 98, in loop
2016-03-15T02:12:46.418512+00:00 app[worker.1]:     self.huey.emit_task(EVENT_ERROR_INTERNAL, task, error=True)
2016-03-15T02:12:46.418512+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/huey/api.py", line 256, in emit_task
2016-03-15T02:12:46.418513+00:00 app[worker.1]:     metadata = self._get_task_metadata(task, error)
2016-03-15T02:12:46.418513+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/huey/api.py", line 236, in _get_task_metadata
2016-03-15T02:12:46.418514+00:00 app[worker.1]:     'id': task.task_id,
2016-03-15T02:12:46.418514+00:00 app[worker.1]: AttributeError: 'NoneType' object has no attribute 'task_id'
```

I had to turn on maintenance, clear the redis DB, and requeue the jobs I needed manually to fix this issue.

There is a chance that the worker server was interrupted during a task, could this have been the issue?  After the worker was rebooted, the original task code may also have been updated.  Could an old call to a function on the redis queue not execute properly to a new version of code?

Any help would be great because I'm a little lost on the matter.

Thanks.

**Comment by Rand01ph** [comment]
I also find this issue，how to resolve it ？

**Comment by coleifer** [comment]
@Rand01ph, how many and what type of worker are you using with the consumer? Can you share any logs showing the issue, or steps to reproduce?

**Comment by Rand01ph** [comment]
@coleifer First time I use huey 1.2.2, which has a Django bug, so It run with only one thread. Today I find about 200 tasks unable to consume, then I find the issue and the Django bug, so I upgrade huey to 1.2.3 and run with 10 threads. After restart uWSGI and huey works, It's also have this issue. So i attempt comment the "periodic_task" and restart the Huey works, quickly all the tasks finished.
I will analyse the program logs tomorrow, now I don't know how to reproduce.
