### ISSUE TITLE
TypeError raised in task.get_data()

### ISSUE THREAD

**Issue by cmanallen** [coleifer/huey#173]
I'm running `huey` locally and everything is fine.  On production, running it causes the below error.  I don't think this is a problem with `huey` but I wanted to see if you had any insights as to how this error is raised.

```
TypeError: 'NoneType' object is not iterable
[2016-07-09 10:16:36,234] INFO:huey.consumer.Worker:Worker-1:Executing queuecmd_delete_expired_tokens: queuecmd_delete_expired_tokens
[2016-07-09 10:16:36,239] ERROR:huey.consumer.Worker:Worker-1:Unhandled exception in worker thread
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/huey/consumer.py", line 144, in process_task
    self.huey.execute(task)
  File "/usr/local/lib/python2.7/dist-packages/huey/api.py", line 283, in execute
    metadata = self._get_task_metadata(task, exc, True)
  File "/usr/local/lib/python2.7/dist-packages/huey/api.py", line 245, in _get_task_metadata
    targs, tkwargs = task.get_data()
TypeError: 'NoneType' object is not iterable
```

**Comment by cmanallen** [comment]
Okay I think I understand the issue.  There was an outbound HTTP request that was failing.
