### ISSUE TITLE
Error running Getting Started on Windows

### ISSUE THREAD

**Issue by prokher** [coleifer/huey#208]
Hello,

I tried to reproduce [Trying it out yourself](https://huey.readthedocs.io/en/latest/getting-started.html#trying-it-out-yourself) on Windows. Installed end started Redis, but get the following error:

```
C:\Users\prokher\Desktop\HueyTest>huey_consumer.py -w 1 -k process main.huey
[2017-03-11 00:30:20,280] INFO:huey.consumer:2688:Huey consumer started with 1 process, PID 2688
[2017-03-11 00:30:20,280] INFO:huey.consumer:2688:Scheduler runs every 1 seconds.
[2017-03-11 00:30:20,280] INFO:huey.consumer:2688:Periodic tasks are enabled.
[2017-03-11 00:30:20,295] INFO:huey.consumer:2688:The following commands are available:
+ count_beans
Traceback (most recent call last):
  File "C:\Program Files\Python36\Scripts\huey_consumer.py", line 49, in <module>
    consumer_main()
  File "C:\Program Files\Python36\Scripts\huey_consumer.py", line 45, in consumer_main
    consumer.run()
  File "c:\program files\python36\lib\site-packages\huey\consumer.py", line 439, in run
    self.start()
  File "c:\program files\python36\lib\site-packages\huey\consumer.py", line 430, in start
    self.scheduler.start()
  File "c:\program files\python36\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "c:\program files\python36\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "c:\program files\python36\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "c:\program files\python36\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "c:\program files\python36\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'Consumer._create_process.<locals>._run'

C:\Users\prokher\Desktop\HueyTest>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\program files\python36\lib\multiprocessing\spawn.py", line 99, in spawn_main
    new_handle = reduction.steal_handle(parent_pid, pipe_handle)
  File "c:\program files\python36\lib\multiprocessing\reduction.py", line 82, in steal_handle
    _winapi.PROCESS_DUP_HANDLE, False, source_pid)
OSError: [WinError 87] The parameter is incorrect
```

What am I doing wrong? (Except running it on Windows ;-) )

**Comment by coleifer** [comment]
IDK, Windows isn't supported with multi-process workers I guess?

**Comment by rahuldeve** [comment]
Ive run into the same issue on a windows machine. The` _run()` function inside the Consumer class is not pickle friendly. I tried changing the `multiprocessing ` library to `multiprocess ` hoping that `dill` would solve the issue but I just got another pickling error:

`TypeError: cannot serialize '_io.TextIOWrapper' object`

This looks like a very low level issue so I think its safe to say that huey will not run on windows with multi-process workers

**Comment by coleifer** [comment]
Theoretically this would only be an issue if you were running huey on a windows server, right? My assumption is that, even if you develop on a Windows machine, you probably deploy your Python to linux most of the time. So using threads on Windows may be acceptable because it's a dev environment.

**Comment by rahuldeve** [comment]
Yes but unfortunately my production server is windows based. For now I think I can create a separate set of "async" functions that calls the normal functions in a newly spawned process and tag those async functions as huey tasks. Anyways I think its best to mention about this issue in the docs somewhere.

**Comment by coleifer** [comment]
Literally nobody should be running Windows.

**Comment by prokher** [comment]
Unfortunately there are multibillion industries where Windows is dominating (e.g. mechanical engineering), so the software developed needs to be cross-platform.

**Comment by ricosuave73** [comment]
Just a suggestion/FYI, there are more Python projects struggling with this problem. I read some projects just writing the issue off as 'not supported on Windows', because Windows doesn't have the fork() system call like Linux does. Instead it uses a spawn() call, which is not the same.
But I also saw a workaround/fix used in the chainer deep-learning framework that replaces _pickle_ with _dill_, which does seems to work for them: https://github.com/chainer/chainerrl/issues/175
