### ISSUE TITLE
Tolerate temporary cache unavailability

### ISSUE THREAD

**Issue by tuukkamustonen** [coleifer/huey#235]
Unfortunately, I don't have much logs about this (since my EC2 instances died), but in case cache becomes unavailable, you will get something like this:

    huey.exceptions.ScheduleReadException: ConnectionError: Error connecting to my_redis_instance.foobar:6379. timed out.

Which will result in huey consumers dying:

    Process Scheduler died!

Would it be better to keep the consumer (or scheduler?) up and keep on retrying? Or at least have retrying (up until some point) as a configurable option.

I know, I could have external (e.g. supervisor) process monitor huey and restart it if it dies, but I would prefer huey itself being more fault-tolerant (for simplicity: no need to run yet another component).

**Comment by coleifer** [comment]
I have avoided consideration of the backend going away...I'm not sure how best to handle that, and part of me feels that using something like supervisor would be the correct way to approach things. That said, Huey should probably be able to tolerate the backend going away for a short time without dying...

**Comment by tuukkamustonen** [comment]
Yeah, so some simple retry loop (wait x, retry y times)?

**Comment by coleifer** [comment]
I believe this should actually address the issue: 0ae06cec00469d5bde2c4bbe8177adad8991112d

Everywhere else in the consumer there appears to be sufficient exception handling code to keep things running if Redis went away for a moment.

**Comment by tuukkamustonen** [comment]
Thanks, two observations:

1) When Redis goes away (locally tested by just shutting down redis), the logs get flooded by:

    2017-07-07 12:04:01,751 - redis - DEBUG - Executed query (0 ms): BRPOP 'huey.redis.localhuey' 20
    2017-07-07 12:04:01,752 - redis - DEBUG - Executed query (0 ms): BRPOP 'huey.redis.localhuey' 20
    2017-07-07 12:04:01,753 - redis - DEBUG - Executed query (0 ms): BRPOP 'huey.redis.localhuey' 20
    ...

Could huey try reconnecting in a little bit of slower pace instead of as quick as possible? Maybe configurable option for delay between retry attempts?

2) Retrying indeed works, after restoring redis, it's back to polling every second instead:

    2017-07-07 12:05:01,166 - redis - DEBUG - Executed query (0 ms): EVALSHA 'a08640cb6d2244b627dffdfd70c3f445d8c9cf2c' 1 'huey.schedule.localhuey' 1499407501.0
    2017-07-07 12:05:02,167 - redis - DEBUG - Executed query (0 ms): EVALSHA 'a08640cb6d2244b627dffdfd70c3f445d8c9cf2c' 1 'huey.schedule.localhuey' 1499407502.0
    2017-07-07 12:05:03,169 - redis - DEBUG - Executed query (0 ms): EVALSHA 'a08640cb6d2244b627dffdfd70c3f445d8c9cf2c' 1 'huey.schedule.localhuey' 1499407503.0

However, the problem is that huey consumer may now eternally stay in a state where it cannot connect to cache. This means connectivity problems can go unnoticed, as the process is there, but it just never works. Would it be possible to specify max retry attempts?

**Comment by coleifer** [comment]
Can you share the full traceback for those exceptions listed in 1?

**Comment by coleifer** [comment]
Looking at the code in the worker, I would have thought that Huey *would* be sleeping if there were problems de-queueing tasks:

```python
    def loop(self, now=None):
        exc_raised = True
        try:
            task = self.huey.dequeue()
        except QueueReadException:
            ...
        except QueueException:
            ...
        else:
            exc_raised = False

        if task:
            self.delay = self.default_delay
            self.handle_task(task, now or self.get_utcnow())
        elif exc_raised or not self.huey.blocking:  # NOTE THIS CONDITIONAL
            self.sleep()

    def sleep(self):
        if self.delay > self.max_delay:
            self.delay = self.max_delay

        self._logger.debug('No messages, sleeping for: %s' % self.delay)
        time.sleep(self.delay)
        self.delay *= self.backoff
```

**Comment by tuukkamustonen** [comment]
Ok this seems to reproduce only when you run with `blocking=True`.

Start:

```
2017-07-07 14:36:47,309 - huey.consumer - INFO - Huey consumer started with 1 thread, PID 6718                                                                                                                                             
2017-07-07 14:36:47,309 - huey.consumer - INFO - Scheduler runs every 1 seconds.                                                                                                                                                           
2017-07-07 14:36:47,310 - huey.consumer - INFO - Periodic tasks are enabled.                                                                                                                                                               
2017-07-07 14:36:47,310 - huey.consumer - INFO - UTC is enabled.                                                                                                                                                                           
2017-07-07 14:36:47,310 - huey.consumer - INFO - The following commands are available:                                                                                                                                                     
+ send_push_messages                                                                                                                                                                                                                       
2017-07-07 14:36:47,311 - redis - DEBUG - Executed query (0 ms): EVALSHA '' 1 'huey.schedule.localhuey' 1499416607.0                                                                                                                       
2017-07-07 14:36:47,311 - redis - DEBUG - Executed query (0 ms): SCRIPT LOAD "local key = KEYS[1]\nlocal unix_ts = ARGV[1]\nlocal res = redis.call('zrangebyscore', key, '-inf', unix_ts)\nif #res and redis.call('zremrangebyscore', key, '-inf', unix_ts) == #res then\n    return res\nend"                                                                                                                                                                                        
2017-07-07 14:36:47,311 - redis - DEBUG - Executed query (0 ms): EVALSHA 'a08640cb6d2244b627dffdfd70c3f445d8c9cf2c' 1 'huey.schedule.localhuey' 1499416607.0                                                                               
2017-07-07 14:36:47,312 - redis - DEBUG - Executed query (1 ms): BRPOP 'huey.redis.localhuey' 20                                                                                                                                           
2017-07-07 14:36:48,312 - redis - DEBUG - Executed query (0 ms): EVALSHA 'a08640cb6d2244b627dffdfd70c3f445d8c9cf2c' 1 'huey.schedule.localhuey' 1499416608.0                                                                               
2017-07-07 14:36:49,317 - redis - DEBUG - Executed query (0 ms): EVALSHA 'a08640cb6d2244b627dffdfd70c3f445d8c9cf2c' 1 'huey.schedule.localhuey' 1499416609.0                                                                               
2017-07-07 14:36:50,319 - redis - DEBUG - Executed query (0 ms): EVALSHA 'a08640cb6d2244b627dffdfd70c3f445d8c9cf2c' 1 'huey.schedule.localhuey' 1499416610.0                                                                               
...

Shutdown Redis:

```
2017-07-07 14:37:11,351 - redis - DEBUG - Executed query (0 ms): EVALSHA 'a08640cb6d2244b627dffdfd70c3f445d8c9cf2c' 1 'huey.schedule.localhuey' 1499416631.0
2017-07-07 14:37:12,352 - redis - DEBUG - Executed query (0 ms): EVALSHA 'a08640cb6d2244b627dffdfd70c3f445d8c9cf2c' 1 'huey.schedule.localhuey' 1499416632.0
2017-07-07 14:37:12,864 - redis - DEBUG - Executed query (0 ms): BRPOP 'huey.redis.localhuey' 20
2017-07-07 14:37:12,866 - redis - DEBUG - Executed query (0 ms): BRPOP 'huey.redis.localhuey' 20
2017-07-07 14:37:12,868 - redis - DEBUG - Executed query (0 ms): BRPOP 'huey.redis.localhuey' 20
2017-07-07 14:37:12,869 - redis - DEBUG - Executed query (0 ms): BRPOP 'huey.redis.localhuey' 20
...<BRPOP continues flooding>...
```

A bit later (see timestamps):

```
2017-07-07 14:37:13,353 - redis - DEBUG - Executed query (0 ms): EVALSHA 'a08640cb6d2244b627dffdfd70c3f445d8c9cf2c' 1 'huey.schedule.localhuey' 1499416633.0
2017-07-07 14:37:13,353 - redis - DEBUG - Executed query (0 ms): BRPOP 'huey.redis.localhuey' 20
2017-07-07 14:37:13,354 - redis - DEBUG - Executed query (0 ms): BRPOP 'huey.redis.localhuey' 20
2017-07-07 14:37:13,354 - redis - DEBUG - Executed query (0 ms): EVALSHA 'a08640cb6d2244b627dffdfd70c3f445d8c9cf2c' 1 'huey.schedule.localhuey' 1499416633.0
2017-07-07 14:37:13,354 - huey.consumer.Scheduler - ERROR - Error reading from task schedule.
Traceback (most recent call last):
  File "/home/musttu/Code/virtualenvs/cosmos/lib/python3.4/site-packages/redis/connection.py", line 129, in _read_from_socket
    raise socket.error(SERVER_CLOSED_CONNECTION_ERROR)
OSError: Connection closed by server.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/musttu/Code/virtualenvs/cosmos/lib/python3.4/site-packages/redis/client.py", line 573, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/home/musttu/Code/virtualenvs/cosmos/lib/python3.4/site-packages/redis/client.py", line 585, in parse_response
    response = connection.read_response()
  File "/home/musttu/Code/virtualenvs/cosmos/lib/python3.4/site-packages/redis/connection.py", line 577, in read_response
    response = self._parser.read_response()
  File "/home/musttu/Code/virtualenvs/cosmos/lib/python3.4/site-packages/redis/connection.py", line 238, in read_response
    response = self._buffer.readline()
  File "/home/musttu/Code/virtualenvs/cosmos/lib/python3.4/site-packages/redis/connection.py", line 168, in readline
    self._read_from_socket()
  File "/home/musttu/Code/virtualenvs/cosmos/lib/python3.4/site-packages/redis/connection.py", line 143, in _read_from_socket
    (e.args,))
redis.exceptions.ConnectionError: Error while reading from socket: ('Connection closed by server.',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/musttu/Code/virtualenvs/cosmos/lib/python3.4/site-packages/redis/connection.py", line 439, in connect
    sock = self._connect()
  File "/home/musttu/Code/virtualenvs/cosmos/lib/python3.4/site-packages/redis/connection.py", line 494, in _connect
    raise err
  File "/home/musttu/Code/virtualenvs/cosmos/lib/python3.4/site-packages/redis/connection.py", line 482, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/musttu/Code/virtualenvs/cosmos/lib/python3.4/site-packages/huey/api.py", line 171, in inner
    return fn(*args, **kwargs)
  File "/home/musttu/Code/virtualenvs/cosmos/lib/python3.4/site-packages/huey/api.py", line 216, in _read_schedule
    return self.storage.read_schedule(ts)
  File "/home/musttu/Code/virtualenvs/cosmos/lib/python3.4/site-packages/huey/storage.py", line 181, in read_schedule
    tasks = self._pop(keys=[self.schedule_key], args=[unix_ts])
  File "/home/musttu/Code/virtualenvs/cosmos/lib/python3.4/site-packages/redis/client.py", line 2694, in __call__
    return client.evalsha(self.sha, len(keys), *args)
  File "/home/musttu/Code/virtualenvs/cosmos/lib/python3.4/site-packages/redis/client.py", line 1944, in evalsha
    return self.execute_command('EVALSHA', sha, numkeys, *keys_and_args)
  File "/home/musttu/Code/virtualenvs/cosmos/lib/python3.4/site-packages/redis/client.py", line 578, in execute_command
    connection.send_command(*args)
  File "/home/musttu/Code/virtualenvs/cosmos/lib/python3.4/site-packages/pastry/extension/redis.py", line 23, in send_command
    super(XConnection, self).send_command(*args)
  File "/home/musttu/Code/virtualenvs/cosmos/lib/python3.4/site-packages/redis/connection.py", line 563, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/home/musttu/Code/virtualenvs/cosmos/lib/python3.4/site-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "/home/musttu/Code/virtualenvs/cosmos/lib/python3.4/site-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:6379. Connection refused.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/musttu/Code/virtualenvs/cosmos/lib/python3.4/site-packages/huey/consumer.py", line 233, in loop
    task_list = self.huey.read_schedule(now or self.get_utcnow())
  File "/home/musttu/Code/virtualenvs/cosmos/lib/python3.4/site-packages/huey/api.py", line 333, in read_schedule
    for m in self._read_schedule(ts)]
  File "/home/musttu/Code/virtualenvs/cosmos/lib/python3.4/site-packages/huey/api.py", line 175, in inner
    wrap_exception(exc_class)
  File "/home/musttu/Code/virtualenvs/cosmos/lib/python3.4/site-packages/huey/utils.py", line 49, in wrap_exception
    raise new_exc_class('%s: %s' % (exc_class.__name__, exc))
huey.exceptions.ScheduleReadException: ConnectionError: Error 111 connecting to 127.0.0.1:6379. Connection refused.
2017-07-07 14:37:13,355 - redis - DEBUG - Executed query (0 ms): BRPOP 'huey.redis.localhuey' 20
2017-07-07 14:37:13,363 - redis - DEBUG - Executed query (0 ms): BRPOP 'huey.redis.localhuey' 20
2017-07-07 14:37:13,363 - redis - DEBUG - Executed query (0 ms): BRPOP 'huey.redis.localhuey' 20
...<BRPOP flooding continues>...
```

This stacktrace is thrown every second.

Then until I start Redis again:

```
2017-07-07 14:37:16,363 - redis - DEBUG - Executed query (0 ms): BRPOP 'huey.redis.localhuey' 20
2017-07-07 14:37:16,364 - redis - DEBUG - Executed query (0 ms): BRPOP 'huey.redis.localhuey' 20
2017-07-07 14:37:16,364 - redis - DEBUG - Executed query (0 ms): BRPOP 'huey.redis.localhuey' 20
2017-07-07 14:37:17,358 - redis - DEBUG - Executed query (0 ms): EVALSHA 'a08640cb6d2244b627dffdfd70c3f445d8c9cf2c' 1 'huey.schedule.localhuey' 1499416637.0
2017-07-07 14:37:17,360 - redis - DEBUG - Executed query (0 ms): SCRIPT LOAD "local key = KEYS[1]\nlocal unix_ts = ARGV[1]\nlocal res = redis.call('zrangebyscore', key, '-inf', unix_ts)\nif #res and redis.call('zremrangebyscore', key, '-inf', unix_ts) == #res then\n    return res\nend"
2017-07-07 14:37:17,361 - redis - DEBUG - Executed query (0 ms): EVALSHA 'a08640cb6d2244b627dffdfd70c3f445d8c9cf2c' 1 'huey.schedule.localhuey' 1499416637.0
2017-07-07 14:37:18,358 - redis - DEBUG - Executed query (0 ms): EVALSHA 'a08640cb6d2244b627dffdfd70c3f445d8c9cf2c' 1 'huey.schedule.localhuey' 1499416638.0
```

And now it's back to polling once per second.
