### ISSUE TITLE
TypeErrorcopy_reg in _reduce_ex

### ISSUE THREAD

**Issue by viperfx** [coleifer/huey#246]
Hi, 

I got this error on sentry. It happens every now and then. Is there something on the devops side that is tuned incorrectly? or is this an internal library error?

Let m know if I can provide more info. Here is the trackback to start with.

```
TypeError: can't pickle traceback objects
  File "huey/consumer.py", line 153, in process_task
    self.huey.execute(task)
  File "huey/api.py", line 277, in execute
    self._put_error(pickle.dumps(metadata))
  File "python2.7/pickle.py", line 1380, in dumps
    Pickler(file, protocol).dump(obj)
  File "python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "python2.7/pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "python2.7/pickle.py", line 669, in _batch_setitems
    save(v)
  File "python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "python2.7/pickle.py", line 425, in save_reduce
    save(state)
  File "python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "python2.7/pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "python2.7/pickle.py", line 669, in _batch_setitems
    save(v)
  File "python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "python2.7/pickle.py", line 425, in save_reduce
    save(state)
  File "python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "python2.7/pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "python2.7/pickle.py", line 669, in _batch_setitems
    save(v)
  File "python2.7/pickle.py", line 306, in save
    rv = reduce(self.proto)
  File "python2.7/copy_reg.py", line 70, in _reduce_ex
    raise TypeError, "can't pickle %s objects" % base.__name__
```

**Comment by coleifer** [comment]
I guess you're probably passing an un-pickle-able object to the task. See if you can pass something else, or implement the pickle protocol for the object.

**Comment by viperfx** [comment]
I have two tasks

```
@db_periodic_task(crontab(minute='*'))
def conditionally_run_other_tasks():
```

```
@db_task()
def send_link(report_id):
```

One has no arguments, and the other has an integer as an argument. They should be pickle-able.

**Comment by coleifer** [comment]
It's something to do with the exception being raised.

**Comment by expresspotato** [comment]
I get this when an exception is raised... Which huey would handle this a bit more gracefully as the exceptions thrown could be out of my control without wrapping them in a try catch.

**Comment by coleifer** [comment]
I'm not sure why it's pickling a traceback? The traceback returned in the metadata is the result of calling `traceback.format_exc()` which returns a string.

**Comment by expresspotato** [comment]
So no original exception is thrown so not even sure why a traceback is being generated...

[2017-12-13 22:00:08,816] INFO:huey.consumer.Worker:10104:Executing helium.tasks.tasks.send_communications_later: 1bb4891a-ab65-4826-9168-addc40716c2d
[2017-12-13 22:00:08,823] ERROR:huey.consumer.Worker:10104:Unhandled exception in worker thread
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/huey/consumer.py", line 168, in process_task
    task_value = self.huey.execute(task)
  File "/usr/lib/python2.7/site-packages/huey/api.py", line 375, in execute
    self._put_error(pickle.dumps(metadata))
  File "/usr/lib64/python2.7/pickle.py", line 1374, in dumps
    Pickler(file, protocol).dump(obj)
  File "/usr/lib64/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/usr/lib64/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python2.7/site-packages/dill/dill.py", line 871, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib64/python2.7/pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/usr/lib64/python2.7/pickle.py", line 663, in _batch_setitems
    save(v)
  File "/usr/lib64/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib64/python2.7/pickle.py", line 419, in save_reduce
    save(state)
  File "/usr/lib64/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python2.7/site-packages/dill/dill.py", line 871, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib64/python2.7/pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/usr/lib64/python2.7/pickle.py", line 663, in _batch_setitems
    save(v)
  File "/usr/lib64/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib64/python2.7/pickle.py", line 419, in save_reduce
    save(state)
  File "/usr/lib64/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python2.7/site-packages/dill/dill.py", line 871, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib64/python2.7/pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/usr/lib64/python2.7/pickle.py", line 663, in _batch_setitems
    save(v)
  File "/usr/lib64/python2.7/pickle.py", line 306, in save
    rv = reduce(self.proto)
  File "/usr/lib64/python2.7/copy_reg.py", line 70, in _reduce_ex
    raise TypeError, "can't pickle %s objects" % base.__name__
TypeError: can't pickle traceback objects

**Comment by Antwan86** [comment]
I have basically the same errors for all my failing tasks.

Everytime it's trying to pickle the **exception object** and it crashes. I have to inspect the traceback of the traceback to find out what's the original error. It's very annoying.

Example:
```
TypeError: a class that defines __slots__ without defining __getstate__ cannot be pickled
  File "huey/consumer.py", line 153, in process_task
    self.huey.execute(task)
  File "huey/api.py", line 277, in execute
    self._put_error(pickle.dumps(metadata))
  File "python2.7/pickle.py", line 1380, in dumps
    Pickler(file, protocol).dump(obj)
  File "python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "python2.7/pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "python2.7/pickle.py", line 669, in _batch_setitems
    save(v)
  File "python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "python2.7/pickle.py", line 425, in save_reduce
    save(state)
  File "python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "python2.7/pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "python2.7/pickle.py", line 669, in _batch_setitems
    save(v)
  File "python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "python2.7/pickle.py", line 731, in save_inst
    save(stuff)
  File "python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "python2.7/pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "python2.7/pickle.py", line 669, in _batch_setitems
    save(v)
  File "python2.7/pickle.py", line 306, in save
    rv = reduce(self.proto)
  File "python2.7/copy_reg.py", line 77, in _reduce_ex
    raise TypeError("a class that defines __slots__ without "
```

Context of the failure:
<img width="926" alt="image" src="https://user-images.githubusercontent.com/3027728/33987332-77db9404-e0b8-11e7-8e76-9af4f08bbf63.png">


Solution:
Serialize the exception object before pickling.


Please reopen and fix the issue.

**Comment by coleifer** [comment]
Wow, I'm not sure what's going on. Exceptions seem to be generally pickle-able to me:

```python
In [1]: import pickle

In [2]: try:
   ...:     1 / 0
   ...: except Exception as exc:
   ...:     pass
   ...: 

In [3]: pickle.dumps(exc)
Out[3]: "cexceptions\nZeroDivisionError\np0\n(S'integer division or modulo by zero'\np1\ntp2\nRp3\n."
```

**Comment by coleifer** [comment]
Given the trouble folks are having I'm going with @Antwan86's suggestion of just using the exception's `repr` instead.

**Comment by Antwan86** [comment]
Exceptions can contain loads of misc data, for example HTTPError contains the request and response objects, both containing references to socket and miscellaneous objects.
So yes it's much better to serialize it beforehand.
