### ISSUE TITLE
a task with include_task raise PicklingError

### ISSUE THREAD

**Issue by Rand01ph** [coleifer/huey#282]
I have a send mail task, if i use task with include_task=True, It can't retry. If i don't not use include_task, it retry OK ,but I need use task_id in worker, so how to fix it ?

**Comment by coleifer** [comment]
Can you share the traceback or anything to help me debug the issue? Where is the exception occurring?

**Comment by Rand01ph** [comment]
Yes, If I send mail fail i will raise SendEmailError


`2017-12-22 11:32:17,199 INFO [8366:MainProcess] /opt/venvs/api/local/lib/python2.7/site-packages/huey/consumer.py consumer consumer.py process_task 170 Executing queuecmd_send_email: 3824d5ee-13b0-497e-bbbd-2c8ba2727e23 3 retries
2017-12-22 11:32:17,207 INFO [8366:MainProcess] /opt/disk2/var/www/test/mail/tasks.py tasks tasks.py send_email 31 send_mail data is NoticeMail object
2017-12-22 11:32:18,010 ERROR [8366:MainProcess] /opt/venvs/api/local/lib/python2.7/site-packages/huey/consumer.py consumer consumer.py process_task 208 Unhandled exception in worker thread
Traceback (most recent call last):
  File "/opt/venvs/api/local/lib/python2.7/site-packages/huey/consumer.py", line 177, in process_task
    task_value = self.huey.execute(task)
  File "/opt/venvs/api/local/lib/python2.7/site-packages/huey/api.py", line 367, in execute
    result = task.execute()
  File "/opt/venvs/api/local/lib/python2.7/site-packages/huey/api.py", line 768, in execute
    return func(*args, **kwargs)
  File "/opt/venvs/api/local/lib/python2.7/site-packages/huey/contrib/djhuey/__init__.py", line 93, in inner
    return fn(*args, **kwargs)
  File "/opt/disk2/var/www/test/mail/tasks.py", line 153, in send_email
    raise SendEmailError
SendEmailError
2017-12-22 11:32:18,012 INFO [8366:MainProcess] /opt/venvs/api/local/lib/python2.7/site-packages/huey/consumer.py consumer consumer.py requeue_task 234 Re-enqueueing task 3824d5ee-13b0-497e-bbbd-2c8ba2727e23, 2 tries left
2017-12-22 11:32:18,013 ERROR [8366:MainProcess] /opt/venvs/api/local/lib/python2.7/site-packages/huey/consumer.py consumer consumer.py _run 466 Process Worker-2 died!
Traceback (most recent call last):
  File "/opt/venvs/api/local/lib/python2.7/site-packages/huey/consumer.py", line 462, in _run
    process.loop()
  File "/opt/venvs/api/local/lib/python2.7/site-packages/huey/consumer.py", line 129, in loop
    self.handle_task(task, now or self.get_now())
  File "/opt/venvs/api/local/lib/python2.7/site-packages/huey/consumer.py", line 145, in handle_task
    self.process_task(task, ts)
  File "/opt/venvs/api/local/lib/python2.7/site-packages/huey/consumer.py", line 228, in process_task
    self.requeue_task(task, self.get_now())
  File "/opt/venvs/api/local/lib/python2.7/site-packages/huey/consumer.py", line 240, in requeue_task
    self.enqueue(task)
  File "/opt/venvs/api/local/lib/python2.7/site-packages/huey/consumer.py", line 87, in enqueue
    self.huey.enqueue(task)
  File "/opt/venvs/api/local/lib/python2.7/site-packages/huey/api.py", line 318, in enqueue
    self._enqueue(self.registry.get_message_for_task(task))
  File "/opt/venvs/api/local/lib/python2.7/site-packages/huey/registry.py", line 61, in get_message_for_task
    task.get_data(),
  File "/usr/lib/python2.7/pickle.py", line 1377, in dumps
    Pickler(file, protocol).dump(obj)
  File "/usr/lib/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python2.7/pickle.py", line 562, in save_tuple
    save(element)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python2.7/pickle.py", line 562, in save_tuple
    save(element)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python2.7/pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/usr/lib/python2.7/pickle.py", line 663, in _batch_setitems
    save(v)
  File "/usr/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python2.7/pickle.py", line 401, in save_reduce
    save(args)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python2.7/pickle.py", line 562, in save_tuple
    save(element)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python2.7/pickle.py", line 751, in save_global
    (obj, module, name))
PicklingError: Can't pickle <class 'mail.tasks.queuecmd_send_email'>: it's not found as mail.tasks.queuecmd_send_email
2017-12-22 11:32:19,760 WARNING [8366:MainProcess] /opt/venvs/api/local/lib/python2.7/site-packages/huey/consumer.py consumer consumer.py check_worker_health 558 Worker 2 died, restarting.
`

**Comment by Rand01ph** [comment]
@coleifer 
I use python2.7 and huey 1.5.6
I find if I change huey api.py line 335 
```python
    def _get_task_metadata(self, task, error=False, include_data=False):
```
to
```python
    def _get_task_metadata(self, task, error=False, include_data=True):
```
It's work OK

**Comment by coleifer** [comment]
Can you try: 06f4c6ede53fb7ab998e7b98a479502b441a3982 and let me know if that addresses the issue? I think it had to do with overriding the class name to be the dotted path (including the decorated function's module).

**Comment by Rand01ph** [comment]
Hi,I try this commit, but still have this ERROR.
I think the problem is when a task whit includ_task raise a error, the function get_message_for_task will dumps a task.get_data(), the data have a class which python pickle can't dump it.

**Comment by coleifer** [comment]
What's the traceback when running the most recent code?

**Comment by coleifer** [comment]
Nevermind, I've written a test-case to replicate. I mistakenly thought I already had such a test but apparently not. Working up a fix now.
