### ISSUE TITLE
run_huey fails to run with --queue parameter

### ISSUE THREAD

**Issue by mojeto** [coleifer/huey#300]
Hi,
running `./manage.py run_huey --queue app-huey-queue` fails with exception:
```Traceback (most recent call last):
  File "./manage.py", line 17, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/pyenv/versions/3.6.2/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/pyenv/versions/3.6.2/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vagrant/pyenv/versions/3.6.2/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/vagrant/pyenv/versions/3.6.2/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/vagrant/pyenv/versions/3.6.2/lib/python3.6/site-packages/huey/contrib/djhuey/management/commands/run_huey.py", line 74, in handle
    print('Run huey on ' + str(HUEY.name))
UnboundLocalError: local variable 'HUEY' referenced before assignment
```

huey version 1.8.0
`app-huey-queue` defined properly in my config.
It fails for any queue (default or non default)

**Comment by coleifer** [comment]
@MarcoGlauser @Sebubu -- ... this is related to your patch so feel free to jump in.

**Comment by coleifer** [comment]
Potentially fixed by: f85efe0a89270436211d71fca80d0a8c849b764b

**Comment by coleifer** [comment]
Considering the types of issues relating to this patch, I've decided to roll it back and have pushed a new release, 1.9.0, that returns to the single huey instance behavior of 1.7 and previous.

Apologies -- I should have been more thorough when reviewing this patch. I should have insisted on better test coverage as well.

**Comment by MarcoGlauser** [comment]
sorry for the trouble you had with this patch. I didn't review it in detail, only fixed the merge conflicts. what are the next steps considering this issue? Do you still want to add it at a later time with better coverage?

**Comment by coleifer** [comment]
No worries, I should have insisted on better test coverage.

Yes, I definitely think it's a great feature, and would merge with a more thorough test-suite.
