### ISSUE TITLE
Error with default configuration & `always_eager`

### ISSUE THREAD

**Issue by tehfink** [coleifer/huey#302]
Following the install documentation here:
http://huey.readthedocs.io/en/latest/installation.html
and the django section here:
http://huey.readthedocs.io/en/latest/django.html
Results in an exception:
`huey.exceptions.ConfigurationError: Consumer cannot be run with Huey instances where always_eager is enabled. Please check your configuration and ensure that "huey.always_eager = False".`

Huey's configuration docs for Django imply that the consumer can be run after adding the `HUEY` dict to settings.py. Further down in that page, this section references synchronous code:
http://huey.readthedocs.io/en/latest/django.html?highlight=django#debug-and-synchronous-execution
I assume this is in relation to asyncio-code?
What's the correct configuration/usage for `always_eager` & Django?

PS: the configuration dict for settings.py from the documentation contains a couple self-referential module paths, e.g.: `settings.DEBUG`, which result in errors (see below).

Traceback:
```console
$ cd /Users/tehfink/Desktop/testing/
$ mkdir django_huey_test
$ cd django_huey_test/
$ virtualenv-3.6 django_huey_test-virtualenv
Using base prefix '/opt/local/Library/Frameworks/Python.framework/Versions/3.6'
New python executable in /Users/tehfink/Desktop/testing/django_huey_test/django_huey_test-virtualenv/bin/python3.6
Also creating executable in /Users/tehfink/Desktop/testing/django_huey_test/django_huey_test-virtualenv/bin/python
Installing setuptools, pip, wheel...done.
$ source django_huey_test-virtualenv/bin/activate
(django_huey_test-virtualenv) $ pip install huey[backends] django
Collecting huey[backends]
Collecting django
  Using cached Django-2.0.3-py3-none-any.whl
Collecting peewee; extra == "backends" (from huey[backends])
Collecting redis; extra == "backends" (from huey[backends])
  Using cached redis-2.10.6-py2.py3-none-any.whl
Collecting pytz (from django)
  Using cached pytz-2018.3-py2.py3-none-any.whl
Installing collected packages: peewee, redis, huey, pytz, django
Successfully installed django-2.0.3 huey-1.9.0 peewee-3.1.5 pytz-2018.3 redis-2.10.6
(django_huey_test-virtualenv) $ django-admin startproject django_huey_test
(django_huey_test-virtualenv) $ cd django_huey_test
(django_huey_test-virtualenv) $ open -e django_huey_test/settings.py
…added default configuration from docs…
(django_huey_test-virtualenv) $ python manage.py makemigrations && python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/tehfink/Desktop/testing/django_huey_test/django_huey_test-virtualenv/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/Users/tehfink/Desktop/testing/django_huey_test/django_huey_test-virtualenv/lib/python3.6/site-packages/django/core/management/__init__.py", line 317, in execute
    settings.INSTALLED_APPS
  File "/Users/tehfink/Desktop/testing/django_huey_test/django_huey_test-virtualenv/lib/python3.6/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/Users/tehfink/Desktop/testing/django_huey_test/django_huey_test-virtualenv/lib/python3.6/site-packages/django/conf/__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "/Users/tehfink/Desktop/testing/django_huey_test/django_huey_test-virtualenv/lib/python3.6/site-packages/django/conf/__init__.py", line 106, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/Users/tehfink/Desktop/testing/django_huey_test/django_huey_test-virtualenv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/tehfink/Desktop/testing/django_huey_test/django_huey_test/django_huey_test/settings.py", line 124, in <module>
    'name': settings.DATABASES['default']['NAME'],  # Use db name for huey.
NameError: name 'settings' is not defined
(django_huey_test-virtualenv) $ open -e django_huey_test/settings.py
…fixed settings.DATABASES & settings.DEBUG references…
(django_huey_test-virtualenv) $ python manage.py makemigrations && python manage.py migrate
No changes detected
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying sessions.0001_initial... OK
(django_huey_test-virtualenv) $ python manage.py run_huey
[2018-03-19 11:39:12,163] WARNING:huey.consumer:MainThread:Consumer initialized with Huey instance that has "always_eager" mode enabled. This must be disabled before the consumer can be run.
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/tehfink/Desktop/testing/django_huey_test/django_huey_test-virtualenv/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/Users/tehfink/Desktop/testing/django_huey_test/django_huey_test-virtualenv/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/tehfink/Desktop/testing/django_huey_test/django_huey_test-virtualenv/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/tehfink/Desktop/testing/django_huey_test/django_huey_test-virtualenv/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/Users/tehfink/Desktop/testing/django_huey_test/django_huey_test-virtualenv/lib/python3.6/site-packages/huey/contrib/djhuey/management/commands/run_huey.py", line 84, in handle
    consumer.run()
  File "/Users/tehfink/Desktop/testing/django_huey_test/django_huey_test-virtualenv/lib/python3.6/site-packages/huey/consumer.py", line 535, in run
    self.start()
  File "/Users/tehfink/Desktop/testing/django_huey_test/django_huey_test-virtualenv/lib/python3.6/site-packages/huey/consumer.py", line 485, in start
    'Consumer cannot be run with Huey instances where always_eager'
huey.exceptions.ConfigurationError: Consumer cannot be run with Huey instances where always_eager is enabled. Please check your configuration and ensure that "huey.always_eager = False".
```

**Comment by coleifer** [comment]
> Further down in that page, this section references synchronous code

It refers to the fact that, when always_eager is set, the tasks are not run by the consumer at all but are called immediately and in the same thread as they were invoked originally. So, instead of the task being put on a queue, read by the consumer, and executed in the consumer's python interpreter -- they are run "inline".

> What's the correct configuration/usage for always_eager & Django?

always_eager is helpful for debugging because it means that, when developing your app, you don't need to run a separate queue and consumer. The tasks execute exactly as if they were normal Python functions.

When developing (DEBUG=True) you should use always_eager.

When in production (DEBUG=False) always_eager should also be False.

**Comment by tehfink** [comment]
Thanks for the explanation! Very helpful
