### ISSUE TITLE
Use MiniHuey with Django and preserve db connections between threads

### ISSUE THREAD

**Issue by viperfx** [coleifer/huey#315]
I currently use Huey as a background worker on Django using Redis. 

I wanted to be able to use MiniHuey for other purposes within the application which are not so CPU bound and seem to be a good fit for its built purpose.

I tried to run it and I got the following error when launching the task:

```DatabaseError: DatabaseWrapper objects created in a thread can only be used in that same thread. The object with alias 'default' was created in thread id 123145441251328 and this is thread id 4486497936.```

Here is my wsgi.py file

```
import os

from django.core.wsgi import get_wsgi_application
from huey.contrib.minimal import MiniHuey
from gevent import monkey; monkey.patch_all()

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "application.settings")


huey = MiniHuey()

huey.start()

application = get_wsgi_application()
```

In my file I did 

```
from huey.contrib.minimal import MiniHuey

mini_huey = MiniHuey()
```

```
class SparkWebhookHandler:

    @mini_huey.task()
    def handle_event(self, payload):
```

Do I have a mis configuration or is MiniHuey not supported with Django at all?

**Comment by coleifer** [comment]
Is there any change when you move "from gevent import monkey; monkey.patch_all()" to the very first line of your WSGI file?

**Comment by viperfx** [comment]
Just tried that change and it still behaves the same. The error occurs when I visit any page of the application. 

here is the full stack trace 

```
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/viperfx/.virtualenvs/scrumbot/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/Users/viperfx/.virtualenvs/scrumbot/lib/python2.7/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/viperfx/.virtualenvs/scrumbot/lib/python2.7/site-packages/django/core/management/base.py", line 296, in run_from_argv
    connections.close_all()
  File "/Users/viperfx/.virtualenvs/scrumbot/lib/python2.7/site-packages/django/db/utils.py", line 234, in close_all
    connection.close()
  File "/Users/viperfx/.virtualenvs/scrumbot/lib/python2.7/site-packages/django/db/backends/base/base.py", line 283, in close
    self.validate_thread_sharing()
  File "/Users/viperfx/.virtualenvs/scrumbot/lib/python2.7/site-packages/django/db/backends/base/base.py", line 542, in validate_thread_sharing
    % (self.alias, self._thread_ident, thread.get_ident())
django.db.utils.DatabaseError: DatabaseWrapper objects created in a thread can only be used in that same thread. The object with alias 'default' was created in thread id 140736170554304 and this is thread id 4383314160.
Exception KeyError: KeyError(4383314160,) in <module 'threading' from '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.pyc'> ignored
```
