### ISSUE TITLE
Cannot import huey package on Windows 10 Anaconda setup

### ISSUE THREAD

**Issue by gchadder3** [coleifer/huey#321]
Hello,

I've tried getting the example in this page
http://huey.readthedocs.io/en/latest/getting-started.html 
to work on my Windows 10 machine with Anaconda installed after following the install directions, and then I got
```
C:\GitRepos\OptimaRepos\Nutrition\nutrition\hueytest>huey_consumer.py main.huey
Traceback (most recent call last):
  File "C:\Users\gchad\Anaconda2\Scripts\huey_consumer.py", line 6, in <module>
    from huey.consumer import Consumer
ImportError: No module named huey.consumer
```
when I tried to start the example.  Investigating further, I opened Spyder (the Anaconda GUI console), and tried to do a simple
`import huey` and got a very long error, the tail of which I've included here:

```
        self._callback = None
        self.args = None
        if self._flags & 1:
            Py_DECREF(<PyObjectPtr>self)
                      ^
------------------------------------------------------------

Anaconda2\lib\site-packages\gevent\libev\corecext.pyx:958:23: 'PyObjectPtr' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
        if self._flags & 6 == 4:
            libev.ev_unref(self.loop._ptr)
            self._flags |= 2
        libev.ev_feed_event(self.loop._ptr, &self._watcher, revents)
        if not self._flags & 1:
            Py_INCREF(<PyObjectPtr>self)
                      ^
------------------------------------------------------------

Anaconda2\lib\site-packages\gevent\libev\corecext.pyx:982:23: 'PyObjectPtr' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
            self._flags |= 2
        if update:
            libev.ev_now_update(self.loop._ptr)
        libev.ev_timer_start(self.loop._ptr, &self._watcher)
        if not self._flags & 1:
            Py_INCREF(<PyObjectPtr>self)
                      ^
------------------------------------------------------------

Anaconda2\lib\site-packages\gevent\libev\corecext.pyx:1000:23: 'PyObjectPtr' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
            self._flags |= 2
        if update:
            libev.ev_now_update(self.loop._ptr)
        libev.ev_timer_again(self.loop._ptr, &self._watcher)
        if not self._flags & 1:
            Py_INCREF(<PyObjectPtr>self)
                      ^
------------------------------------------------------------

Anaconda2\lib\site-packages\gevent\libev\corecext.pyx:1046:23: 'PyObjectPtr' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...

        def __get__(self):
            return self._callback

        def __set__(self, object callback):
            if not PyCallable_Check(<PyObjectPtr>callback) and callback is not None:
                                    ^
------------------------------------------------------------

Anaconda2\lib\site-packages\gevent\libev\corecext.pyx:1088:37: 'PyObjectPtr' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
            self._flags &= ~2
        libev.ev_signal_stop(self.loop._ptr, &self._watcher)
        self._callback = None
        self.args = None
        if self._flags & 1:
            Py_DECREF(<PyObjectPtr>self)
                      ^
------------------------------------------------------------

Anaconda2\lib\site-packages\gevent\libev\corecext.pyx:1103:23: 'PyObjectPtr' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
        if self._flags & 6 == 4:
            libev.ev_unref(self.loop._ptr)
            self._flags |= 2
        libev.ev_feed_event(self.loop._ptr, &self._watcher, revents)
        if not self._flags & 1:
            Py_INCREF(<PyObjectPtr>self)
                      ^
------------------------------------------------------------

Anaconda2\lib\site-packages\gevent\libev\corecext.pyx:1127:23: 'PyObjectPtr' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
        if self._flags & 6 == 4:
            libev.ev_unref(self.loop._ptr)
            self._flags |= 2
        libev.ev_signal_start(self.loop._ptr, &self._watcher)
        if not self._flags & 1:
            Py_INCREF(<PyObjectPtr>self)
                      ^
------------------------------------------------------------

Anaconda2\lib\site-packages\gevent\libev\corecext.pyx:1143:23: 'PyObjectPtr' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...

        def __get__(self):
            return self._callback

        def __set__(self, object callback):
            if not PyCallable_Check(<PyObjectPtr>callback) and callback is not None:
                                    ^
------------------------------------------------------------

Anaconda2\lib\site-packages\gevent\libev\corecext.pyx:1213:37: 'PyObjectPtr' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
            self._flags &= ~2
        libev.ev_idle_stop(self.loop._ptr, &self._watcher)
        self._callback = None
        self.args = None
        if self._flags & 1:
            Py_DECREF(<PyObjectPtr>self)
                      ^
------------------------------------------------------------

Anaconda2\lib\site-packages\gevent\libev\corecext.pyx:1228:23: 'PyObjectPtr' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
        if self._flags & 6 == 4:
            libev.ev_unref(self.loop._ptr)
            self._flags |= 2
        libev.ev_feed_event(self.loop._ptr, &self._watcher, revents)
        if not self._flags & 1:
            Py_INCREF(<PyObjectPtr>self)
                      ^
------------------------------------------------------------

Anaconda2\lib\site-packages\gevent\libev\corecext.pyx:1252:23: 'PyObjectPtr' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
        if self._flags & 6 == 4:
            libev.ev_unref(self.loop._ptr)
            self._flags |= 2
        libev.ev_idle_start(self.loop._ptr, &self._watcher)
        if not self._flags & 1:
            Py_INCREF(<PyObjectPtr>self)
                      ^
------------------------------------------------------------

Anaconda2\lib\site-packages\gevent\libev\corecext.pyx:1268:23: 'PyObjectPtr' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...

        def __get__(self):
            return self._callback

        def __set__(self, object callback):
            if not PyCallable_Check(<PyObjectPtr>callback) and callback is not None:
                                    ^
------------------------------------------------------------

Anaconda2\lib\site-packages\gevent\libev\corecext.pyx:1332:37: 'PyObjectPtr' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
            self._flags &= ~2
        libev.ev_prepare_stop(self.loop._ptr, &self._watcher)
        self._callback = None
        self.args = None
        if self._flags & 1:
            Py_DECREF(<PyObjectPtr>self)
                      ^
------------------------------------------------------------

Anaconda2\lib\site-packages\gevent\libev\corecext.pyx:1347:23: 'PyObjectPtr' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
        if self._flags & 6 == 4:
            libev.ev_unref(self.loop._ptr)
            self._flags |= 2
        libev.ev_feed_event(self.loop._ptr, &self._watcher, revents)
        if not self._flags & 1:
            Py_INCREF(<PyObjectPtr>self)
                      ^
------------------------------------------------------------

Anaconda2\lib\site-packages\gevent\libev\corecext.pyx:1371:23: 'PyObjectPtr' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
        if self._flags & 6 == 4:
            libev.ev_unref(self.loop._ptr)
            self._flags |= 2
        libev.ev_prepare_start(self.loop._ptr, &self._watcher)
        if not self._flags & 1:
            Py_INCREF(<PyObjectPtr>self)
                      ^
------------------------------------------------------------

Anaconda2\lib\site-packages\gevent\libev\corecext.pyx:1387:23: 'PyObjectPtr' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...

        def __get__(self):
            return self._callback

        def __set__(self, object callback):
            if not PyCallable_Check(<PyObjectPtr>callback) and callback is not None:
                                    ^
------------------------------------------------------------

Anaconda2\lib\site-packages\gevent\libev\corecext.pyx:1451:37: 'PyObjectPtr' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
            self._flags &= ~2
        libev.ev_check_stop(self.loop._ptr, &self._watcher)
        self._callback = None
        self.args = None
        if self._flags & 1:
            Py_DECREF(<PyObjectPtr>self)
                      ^
------------------------------------------------------------

Anaconda2\lib\site-packages\gevent\libev\corecext.pyx:1466:23: 'PyObjectPtr' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
        if self._flags & 6 == 4:
            libev.ev_unref(self.loop._ptr)
            self._flags |= 2
        libev.ev_feed_event(self.loop._ptr, &self._watcher, revents)
        if not self._flags & 1:
            Py_INCREF(<PyObjectPtr>self)
                      ^
------------------------------------------------------------

Anaconda2\lib\site-packages\gevent\libev\corecext.pyx:1490:23: 'PyObjectPtr' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
        if self._flags & 6 == 4:
            libev.ev_unref(self.loop._ptr)
            self._flags |= 2
        libev.ev_check_start(self.loop._ptr, &self._watcher)
        if not self._flags & 1:
            Py_INCREF(<PyObjectPtr>self)
                      ^
------------------------------------------------------------

Anaconda2\lib\site-packages\gevent\libev\corecext.pyx:1506:23: 'PyObjectPtr' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...

        def __get__(self):
            return self._callback

        def __set__(self, object callback):
            if not PyCallable_Check(<PyObjectPtr>callback) and callback is not None:
                                    ^
------------------------------------------------------------

Anaconda2\lib\site-packages\gevent\libev\corecext.pyx:1570:37: 'PyObjectPtr' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
            self._flags &= ~2
        libev.ev_fork_stop(self.loop._ptr, &self._watcher)
        self._callback = None
        self.args = None
        if self._flags & 1:
            Py_DECREF(<PyObjectPtr>self)
                      ^
------------------------------------------------------------

Anaconda2\lib\site-packages\gevent\libev\corecext.pyx:1585:23: 'PyObjectPtr' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
        if self._flags & 6 == 4:
            libev.ev_unref(self.loop._ptr)
            self._flags |= 2
        libev.ev_feed_event(self.loop._ptr, &self._watcher, revents)
        if not self._flags & 1:
            Py_INCREF(<PyObjectPtr>self)
                      ^
------------------------------------------------------------

Anaconda2\lib\site-packages\gevent\libev\corecext.pyx:1609:23: 'PyObjectPtr' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
        if self._flags & 6 == 4:
            libev.ev_unref(self.loop._ptr)
            self._flags |= 2
        libev.ev_fork_start(self.loop._ptr, &self._watcher)
        if not self._flags & 1:
            Py_INCREF(<PyObjectPtr>self)
                      ^
------------------------------------------------------------

Anaconda2\lib\site-packages\gevent\libev\corecext.pyx:1625:23: 'PyObjectPtr' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...

        def __get__(self):
            return self._callback

        def __set__(self, object callback):
            if not PyCallable_Check(<PyObjectPtr>callback) and callback is not None:
                                    ^
------------------------------------------------------------

Anaconda2\lib\site-packages\gevent\libev\corecext.pyx:1689:37: 'PyObjectPtr' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
            self._flags &= ~2
        libev.ev_async_stop(self.loop._ptr, &self._watcher)
        self._callback = None
        self.args = None
        if self._flags & 1:
            Py_DECREF(<PyObjectPtr>self)
                      ^
------------------------------------------------------------

Anaconda2\lib\site-packages\gevent\libev\corecext.pyx:1704:23: 'PyObjectPtr' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
        if self._flags & 6 == 4:
            libev.ev_unref(self.loop._ptr)
            self._flags |= 2
        libev.ev_feed_event(self.loop._ptr, &self._watcher, revents)
        if not self._flags & 1:
            Py_INCREF(<PyObjectPtr>self)
                      ^
------------------------------------------------------------

Anaconda2\lib\site-packages\gevent\libev\corecext.pyx:1728:23: 'PyObjectPtr' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
        if self._flags & 6 == 4:
            libev.ev_unref(self.loop._ptr)
            self._flags |= 2
        libev.ev_async_start(self.loop._ptr, &self._watcher)
        if not self._flags & 1:
            Py_INCREF(<PyObjectPtr>self)
                      ^
------------------------------------------------------------

Anaconda2\lib\site-packages\gevent\libev\corecext.pyx:1744:23: 'PyObjectPtr' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...

        def __get__(self):
            return self._callback

        def __set__(self, object callback):
            if not PyCallable_Check(<PyObjectPtr>callback) and callback is not None:
                                    ^
------------------------------------------------------------

Anaconda2\lib\site-packages\gevent\libev\corecext.pyx:1815:37: 'PyObjectPtr' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
            self._flags &= ~2
        libev.ev_child_stop(self.loop._ptr, &self._watcher)
        self._callback = None
        self.args = None
        if self._flags & 1:
            Py_DECREF(<PyObjectPtr>self)
                      ^
------------------------------------------------------------

Anaconda2\lib\site-packages\gevent\libev\corecext.pyx:1830:23: 'PyObjectPtr' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
        if self._flags & 6 == 4:
            libev.ev_unref(self.loop._ptr)
            self._flags |= 2
        libev.ev_feed_event(self.loop._ptr, &self._watcher, revents)
        if not self._flags & 1:
            Py_INCREF(<PyObjectPtr>self)
                      ^
------------------------------------------------------------

Anaconda2\lib\site-packages\gevent\libev\corecext.pyx:1854:23: 'PyObjectPtr' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
        if self._flags & 6 == 4:
            libev.ev_unref(self.loop._ptr)
            self._flags |= 2
        libev.ev_child_start(self.loop._ptr, &self._watcher)
        if not self._flags & 1:
            Py_INCREF(<PyObjectPtr>self)
                      ^
------------------------------------------------------------

Anaconda2\lib\site-packages\gevent\libev\corecext.pyx:1870:23: 'PyObjectPtr' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...

        def __get__(self):
            return self._callback

        def __set__(self, object callback):
            if not PyCallable_Check(<PyObjectPtr>callback) and callback is not None:
                                    ^
------------------------------------------------------------

Anaconda2\lib\site-packages\gevent\libev\corecext.pyx:1960:37: 'PyObjectPtr' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
            self._flags &= ~2
        libev.ev_stat_stop(self.loop._ptr, &self._watcher)
        self._callback = None
        self.args = None
        if self._flags & 1:
            Py_DECREF(<PyObjectPtr>self)
                      ^
------------------------------------------------------------

Anaconda2\lib\site-packages\gevent\libev\corecext.pyx:1975:23: 'PyObjectPtr' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
        if self._flags & 6 == 4:
            libev.ev_unref(self.loop._ptr)
            self._flags |= 2
        libev.ev_feed_event(self.loop._ptr, &self._watcher, revents)
        if not self._flags & 1:
            Py_INCREF(<PyObjectPtr>self)
                      ^
------------------------------------------------------------

Anaconda2\lib\site-packages\gevent\libev\corecext.pyx:1999:23: 'PyObjectPtr' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
        if self._flags & 6 == 4:
            libev.ev_unref(self.loop._ptr)
            self._flags |= 2
        libev.ev_stat_start(self.loop._ptr, &self._watcher)
        if not self._flags & 1:
            Py_INCREF(<PyObjectPtr>self)
                      ^
------------------------------------------------------------

Anaconda2\lib\site-packages\gevent\libev\corecext.pyx:2015:23: 'PyObjectPtr' is not a type identifier
```

**Comment by coleifer** [comment]
Looks like a problem with `gevent`... I'd suggest you open an issue there.

**Comment by gchadder3** [comment]
I just tried `import gevent` and it fails in a similar way, so I guess this is probably an installation problem with `gevent` on my machine.

**Comment by gchadder3** [comment]
I had some problems uninstalling and reinstalling `gevent`, but after resolving those, both `gevent` and `huey` import within both Spyder and the python interpreter.  However, for some reason, when I still get:
```
C:\GitRepos\OptimaRepos\Nutrition\nutrition\hueytest>huey_consumer.py main.huey
Traceback (most recent call last):
  File "C:\Users\gchad\Anaconda2\Scripts\huey_consumer.py", line 6, in <module>
    from huey.consumer import Consumer
ImportError: No module named huey.consumer
```

Not sure why things would import in Spyder and python, but fail from the script.
