### ISSUE TITLE
OSError: [WinError 87] by using huey_consumer.py main.huey -k process -w 2 on windows 10

### ISSUE THREAD

**Issue by sh601857** [coleifer/huey#323]
huey_consumer.py main.huey -k process -w 2
[2018-06-22 22:33:51,446] INFO:huey.consumer:12244:Huey consumer started with 2 process, PID 12244
[2018-06-22 22:33:51,446] INFO:huey.consumer:12244:Scheduler runs every 1 second(s).
[2018-06-22 22:33:51,446] INFO:huey.consumer:12244:Periodic tasks are enabled.
[2018-06-22 22:33:51,447] INFO:huey.consumer:12244:UTC is enabled.
[2018-06-22 22:33:51,447] INFO:huey.consumer:12244:The following commands are available:
+ queue_task_count_beans
+ queue_task_try_thrice
Traceback (most recent call last):
  File "C:\Users\yijio\AppData\Local\Programs\Python\Python36\Scripts\huey_consumer.py", line 51, in <module>
    consumer_main()
  File "C:\Users\yijio\AppData\Local\Programs\Python\Python36\Scripts\huey_consumer.py", line 47, in consumer_main
    consumer.run()
  File "c:\users\yijio\appdata\local\programs\python\python36\lib\site-packages\huey\consumer.py", line 662, in run
    self.start()
  File "c:\users\yijio\appdata\local\programs\python\python36\lib\site-packages\huey\consumer.py", line 630, in start
    self.scheduler.start()
  File "c:\users\yijio\appdata\local\programs\python\python36\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "c:\users\yijio\appdata\local\programs\python\python36\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "c:\users\yijio\appdata\local\programs\python\python36\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "c:\users\yijio\appdata\local\programs\python\python36\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "c:\users\yijio\appdata\local\programs\python\python36\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'Consumer._create_process.<locals>._run'

D:\Workspace\Test\huey_test>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\users\yijio\appdata\local\programs\python\python36\lib\multiprocessing\spawn.py", line 99, in spawn_main
    new_handle = reduction.steal_handle(parent_pid, pipe_handle)
  File "c:\users\yijio\appdata\local\programs\python\python36\lib\multiprocessing\reduction.py", line 82, in steal_handle
    _winapi.PROCESS_DUP_HANDLE, False, source_pid)
OSError: [WinError 87] 参数错误。

**Comment by coleifer** [comment]
Multiprocessing doesn't work on Windoze. #208

**Comment by NotoriousRebel** [comment]
@coleifer two years late but what you said is just factually incorrect, I encourage you to check out, [https://github.com/omnilib/aiomultiprocess](https://github.com/omnilib/aiomultiprocess) to see what AsyncIO and multiprocessing can bring to the table.
