### ISSUE TITLE
Huey with pyzmq (ZMQ)

### ISSUE THREAD

**Issue by surfingkaka** [coleifer/huey#348]
Exploring to see if I can use Huey with zmq, I have the following error (edits for clarity)

```
  Traceback (most recent call last):
    File "main.py", line 10, in <module>
      count_beans(ctx)
    File "XXXXXXXminiconda2/lib/python2.7/site-packages/huey/api.py", line 635, in __call__
      return self.huey.enqueue(self.s(*args, **kwargs))
    File "XXXXXXXminiconda2/lib/python2.7/site-packages/huey/api.py", line 306, in enqueue
      self._enqueue(self.registry.get_message_for_task(task))
    File "XXXXXXXminiconda2/lib/python2.7/site-packages/huey/registry.py", line 67, in get_message_for_task
      on_complete))
    File "XXXXXXXminiconda2/lib/python2.7/pickle.py", line 1380, in dumps
      Pickler(file, protocol).dump(obj)
    File "XXXXXXXminiconda2/lib/python2.7/pickle.py", line 224, in dump
      self.save(obj)
    File "XXXXXXXminiconda2/lib/python2.7/pickle.py", line 286, in save
      f(self, obj) # Call unbound method with explicit self
    File "XXXXXXXminiconda2/lib/python2.7/pickle.py", line 568, in save_tuple
      save(element)
    File "XXXXXXXminiconda2/lib/python2.7/pickle.py", line 286, in save
      f(self, obj) # Call unbound method with explicit self
    File "XXXXXXXminiconda2/lib/python2.7/pickle.py", line 568, in save_tuple
      save(element)
    File "XXXXXXXminiconda2/lib/python2.7/pickle.py", line 286, in save
      f(self, obj) # Call unbound method with explicit self
    File "XXXXXXXminiconda2/lib/python2.7/pickle.py", line 568, in save_tuple
      save(element)
    File "XXXXXXXminiconda2/lib/python2.7/pickle.py", line 306, in save
      rv = reduce(self.proto)
    File "stringsource", line 2, in zmq.backend.cython.context.Context.__reduce_cython__
  TypeError: no default __reduce__ due to non-trivial __cinit__
```

with this code :

main.py

    from config import huey
    from tasks import count_beans
    import random
    import zmq

    if __name__ == '__main__':
         ctx = zmq.Context.instance()
         for i in range(random.randint(1,5)):
             count_beans(ctx)
          print('Enqueued job to count %s beans' % 34)`

tasks.py
    
    from config import huey
    import zmq

    @huey.task()
    def count_beans(ctx):
         #ctx =zmq.Context.instance()
         socket=ctx.socket(zmq.REQ)
         socket.connect("tcp://localhost:5560")
         for i in range(3):
             print("sending..")
             socket.send("Hello from Huey")
             msg = socket.recv()
             print("Recv'd : ",msg)
         print('-- counted %s beans -- ' % num)

And my zmq app which is receiving messages 

    import zmq
    import time

    ctx =zmq.Context.instance()
    socket=ctx.socket(zmq.REP)
    socket.bind("tcp://*:5560")

    while True:
        msg=socket.recv()
        print("recv'd : ",msg)
        time.sleep(1)
        socket.send("Huey works!!")

any ideas on how to troubleshoot ? Suspect that it might be a pickling of the zmq.context issue, but maybe someone has a solution
thanks very much

**Comment by coleifer** [comment]
You can't pickle a zmq context, simple as that.
