### ISSUE TITLE
huey.result() won't raise TaskException if task failed with an exception

### ISSUE THREAD

**Issue by MisLink** [coleifer/huey#364]
Sample code:

```python
# config.py
from huey import RedisHuey

huey = RedisHuey()
```

```python
# task.py
from config import huey


@huey.task()
def failed():
    raise ValueError("failed!")
```

```python
# main.py
from config import huey
from task import failed
```

then run:
```ipython
In [1]: from config import huey

In [2]: from task import failed

In [3]: r = failed()

In [4]: e = huey.result(r.task.task_id)

In [5]: type(e)
Out[5]: huey.utils.Error
```
It will return an `Error` object instead of raising a exception, but [doc](https://huey.readthedocs.io/en/latest/api.html#Huey.result) said a `TaskException` wiil be raised.

consumer log:
```shell
$ huey_consumer.py main.huey
[2018-09-26 12:03:36,559] INFO:huey.consumer:MainThread:Huey consumer started with 1 thread, PID 22928
[2018-09-26 12:03:36,559] INFO:huey.consumer:MainThread:Scheduler runs every 1 second(s).
[2018-09-26 12:03:36,559] INFO:huey.consumer:MainThread:Periodic tasks are enabled.
[2018-09-26 12:03:36,559] INFO:huey.consumer:MainThread:UTC is enabled.
[2018-09-26 12:03:36,560] INFO:huey.consumer:MainThread:The following commands are available:
+ queue_task_failed
[2018-09-26 12:04:34,465] INFO:huey.consumer.Worker:Worker-1:Executing task.queue_task_failed: f1406f9f-a5cc-4f39-ab12-31dc42daa410
[2018-09-26 12:04:34,469] ERROR:huey.consumer.Worker:Worker-1:Unhandled exception in worker thread
Traceback (most recent call last):
  File "/Users/<me>/projects/test_huey/.venv/lib/python3.6/site-packages/huey/consumer.py", line 241, in process_task
    task_value = self.huey.execute(task)
  File "/Users/<me>/projects/test_huey/.venv/lib/python3.6/site-packages/huey/api.py", line 380, in execute
    result = task.execute()
  File "/Users/<me>/projects/test_huey/.venv/lib/python3.6/site-packages/huey/api.py", line 880, in execute
    return func(*args, **kwargs)
  File "/Users/<me>/projects/test_huey/task.py", line 6, in failed
    raise ValueError("failed!")
ValueError: failed!
```

**Comment by coleifer** [comment]
In your example, resolving the `r` object to get the result will raise the error:

```python
r = failed()
actual_result = r()  # Exception raised.
```

There appears to be an inconsistency in the `result()` API, however, which your example illustrates.

I've pushed a fix in 2ac97394661b86edba450a1155859a1a642d6503
