### ISSUE TITLE
module 'huey' has no attribute 'RedisExpireStorage'

### ISSUE THREAD

**Issue by jedie** [coleifer/huey#421]
I updated to huey v2.1.0 and would like to use the new `RedisExpireStorage`
So i set:
```
HUEY = {
    ...
    "backend_class": "huey.RedisExpireStorage", 
    ...
}
```

But then i get:
```
Error: could not import Huey backend:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/huey/contrib/djhuey/__init__.py", line 95, in <module>
    backend_cls = get_backend(backend_path)
  File "/usr/local/lib/python3.6/site-packages/huey/contrib/djhuey/__init__.py", line 59, in get_backend
    return getattr(module, class_name)
AttributeError: module 'huey' has no attribute 'RedisExpireStorage'
```

**Comment by coleifer** [comment]
You use `RedisExpireHuey`, not the storage. If you want to specify a storage implementation, use `storage_class` argument.

**Comment by jedie** [comment]
Ah! Thanks!
