### ISSUE TITLE
Running tasks from periodic task

### ISSUE THREAD

**Issue by etienne-napoleone** [coleifer/huey#448]
Hello,
I'm trying to run tasks from a periodic task following this scheme:
```python
import time

from huey import crontab
from huey import MemoryHuey

huey = MemoryHuey()


@huey.task()
def sleep(n: int):
    print(f"Sleeping {n}!")
    time.sleep(n)
    return n


@huey.periodic_task(crontab(minute="*"))
def sleeper():
    print("Let's sleep")
    result = sleep(5)
    print("I slept for {}".format(result(blocking=True, timeout=10)))
```

When starting a consumer, it end up doing this:
- Enqueuing sleeper
- Executing sleeper
  - the result data will never be available
  - because of the timeout it raises HueyException: timed out waiting for result
- For some reason the call to sleep() is executed after raising the exception

```
➜ huey_consumer.py app.huey
[2019-09-10 15:36:58,308] INFO:huey.consumer:MainThread:Huey consumer started with 1 thread, PID 14231 at 2019-09-10 06:36:58.308656
[2019-09-10 15:36:58,308] INFO:huey.consumer:MainThread:Scheduler runs every 1 second(s).
[2019-09-10 15:36:58,309] INFO:huey.consumer:MainThread:Periodic tasks are enabled.
[2019-09-10 15:36:58,309] INFO:huey.consumer:MainThread:The following commands are available:
+ app.sleep
+ app.sleeper
[2019-09-10 15:36:58,309] INFO:huey.consumer.Scheduler:Scheduler:Enqueueing periodic task app.sleeper: 3cc1c390-9175-487c-802a-214ec816e292.
[2019-09-10 15:36:58,309] INFO:huey:Worker-1:Executing app.sleeper: 3cc1c390-9175-487c-802a-214ec816e292
Let's sleep
[2019-09-10 15:37:08,877] ERROR:huey:Worker-1:Unhandled exception in task 3cc1c390-9175-487c-802a-214ec816e292.
Traceback (most recent call last):
  File "/Users/etienne/Library/Caches/pypoetry/virtualenvs/oracle-py3.7/lib/python3.7/site-packages/huey/api.py", line 342, in _execute
    task_value = task.execute()
  File "/Users/etienne/Library/Caches/pypoetry/virtualenvs/oracle-py3.7/lib/python3.7/site-packages/huey/api.py", line 691, in execute
    return func(*args, **kwargs)
  File "/Users/etienne/Work/repo/terra-project/oracle/app.py", line 21, in sleeper
    print("I slept for {}".format(result(blocking=True, timeout=10)))
  File "/Users/etienne/Library/Caches/pypoetry/virtualenvs/oracle-py3.7/lib/python3.7/site-packages/huey/api.py", line 821, in __call__
    return self.get(*args, **kwargs)
  File "/Users/etienne/Library/Caches/pypoetry/virtualenvs/oracle-py3.7/lib/python3.7/site-packages/huey/api.py", line 861, in get
    revoke_on_timeout, preserve)
  File "/Users/etienne/Library/Caches/pypoetry/virtualenvs/oracle-py3.7/lib/python3.7/site-packages/huey/api.py", line 849, in get_raw_result
    raise HueyException('timed out waiting for result')
huey.exceptions.HueyException: timed out waiting for result
[2019-09-10 15:37:08,879] INFO:huey:Worker-1:Executing app.sleep: 9e04559a-ad93-4c54-a022-31fbca226d10
Sleeping 5!
[2019-09-10 15:37:13,882] INFO:huey:Worker-1:app.sleep: 9e04559a-ad93-4c54-a022-31fbca226d10 executed in 5.003s
^C[2019-09-10 15:37:21,951] INFO:huey.consumer:MainThread:Received SIGINT
[2019-09-10 15:37:21,951] INFO:huey.consumer:MainThread:Shutting down gracefully...
[2019-09-10 15:37:22,763] INFO:huey.consumer:MainThread:All workers have stopped.
[2019-09-10 15:37:22,763] INFO:huey.consumer:MainThread:Consumer exiting.
```

I'm obviously missing something there as for some reasons it is still executing sleep() afterward.

Thanks in advance

**Comment by etienne-napoleone** [comment]
Ah ok actually makes sense, I'd need two consumers as the first one is already executing a task ... closing that.

**Comment by coleifer** [comment]
> two consumers

two workers.

Or just don't block on resolving the result.
