### ISSUE TITLE
Issue Deploying to Heroku

### ISSUE THREAD

**Issue by MandelaK** [coleifer/huey#471]
Hi, I'm having some trouble deploying my app to heroku. I keep getting a weird error during the release phase. Here is the traceback I'm getting from Heroku. 

```


Traceback (most recent call last):

  File "cargotracker/manage.py", line 21, in <module>

    main()

  File "cargotracker/manage.py", line 17, in main

    execute_from_command_line(sys.argv)

  File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line

    utility.execute()

  File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute

    django.setup()

  File "/app/.heroku/python/lib/python3.6/site-packages/django/__init__.py", line 24, in setup

    apps.populate(settings.INSTALLED_APPS)

  File "/app/.heroku/python/lib/python3.6/site-packages/django/apps/registry.py", line 91, in populate

    app_config = AppConfig.create(entry)

  File "/app/.heroku/python/lib/python3.6/site-packages/django/apps/config.py", line 90, in create

    module = import_module(entry)

  File "/app/.heroku/python/lib/python3.6/importlib/__init__.py", line 126, in import_module

    return _bootstrap._gcd_import(name[level:], package, level)

  File "<frozen importlib._bootstrap>", line 994, in _gcd_import

  File "<frozen importlib._bootstrap>", line 971, in _find_and_load

  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked

  File "<frozen importlib._bootstrap_external>", line 678, in exec_module

  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "/app/.heroku/python/lib/python3.6/site-packages/huey/contrib/djhuey/__init__.py", line 100, in <module>

    HUEY = backend_cls(name, **huey_config)

  File "/app/.heroku/python/lib/python3.6/site-packages/huey/api.py", line 111, in __init__

    self.storage = self.create_storage()

  File "/app/.heroku/python/lib/python3.6/site-packages/huey/api.py", line 128, in create_storage

    return self.get_storage(**self.storage_kwargs)

  File "/app/.heroku/python/lib/python3.6/site-packages/huey/api.py", line 140, in get_storage

    return Storage(self.name, **kwargs)

  File "/app/.heroku/python/lib/python3.6/site-packages/huey/storage.py", line 394, in __init__

    self.name = self.clean_name(name)

  File "/app/.heroku/python/lib/python3.6/site-packages/huey/storage.py", line 407, in clean_name

    return re.sub('[^a-z0-9]', '', name)

  File "/app/.heroku/python/lib/python3.6/re.py", line 191, in sub

    return _compile(pattern, flags).sub(repl, string, count)

TypeError: expected string or bytes-like object
```

Here is a sample of my Procfile ...

```
release: python carogtracker/manage.py makemigrations authentication branches cargo orders
release: python cargotracker/manage.py migrate

release: python cargotracker/manage.py runscript create_admin --script-args email="admin@admin.admin"

worker: python cargotracker/manage.py run_huey

web: gunicorn cargotracker.wsgi
```

I can run all dynos locally, but when I push to Heroku, I get that error, please help ...

**Comment by coleifer** [comment]
Huey expects the Huey "name" to be a string. I'm wondering if maybe you're pulling something from the environment, because you're passing a bytes object rather than a string.

**Comment by coleifer** [comment]
If you don't specify a "name" then huey defaults to using your database's name, so that's probably what's happening. Just explicitly specify a name in your settings, e.g.

```python
HUEY = {
    'name': 'huey-app',
    ...
```

**Comment by MandelaK** [comment]
> 
> 
> If you don't specify a "name" then huey defaults to using your database's name, so that's probably what's happening. Just explicitly specify a name in your settings, e.g.
> 
> ```python
> HUEY = {
>     'name': 'huey-app',
>     ...
> ```

Thanks so much for the quick reply. This got rid of the error. I really appreciate your work. Have a good day.
