### ISSUE TITLE
Redis Cluster not working after using custom Huey class

### ISSUE THREAD

**Issue by SanketDG** [coleifer/huey#500]
I have this Redis Cluster setup of 3 masters and 3 slaves, and I am able to read/write values using the standard driver given in [redis-py-cluster](https://pypi.org/project/redis-py-cluster/)

Unfortunately, I can't seem to make it work with Huey and Django.

Here is the Huey configuration from settings.py:

```python
HUEY = {
    'huey_class': 'custom.utils.CustomRedisHuey',  # Huey implementation to use.
    'name': 'custom-task-queue',  # Use db name for huey.
    'results': True,  # Store return values of tasks.
    'store_none': False,  # If a task returns None, do not save to results.
    'immediate': False,  # If DEBUG=True, run synchronously.
    'utc': True,  # Use UTC for all times internally.
    'blocking': True,  # Perform blocking pop rather than poll Redis.
    'connection': {
        'host': 'custom-data-store',
        'port': 6379,
        'db': 0,
        # 'connection_pool': pool,  # Definitely you should use pooling!
        # ... tons of other options, see redis-py for details.

        # huey-specific connection parameters.
        'read_timeout': 1,  # If not polling (blocking pop), use timeout.
        # 'url': None,  # Allow Redis config via a DSN.
    },
    'consumer': {
        'workers': 100,
        'worker_type': 'greenlet',
        'initial_delay': 0.1,  # Smallest polling interval, same as -d.
        'backoff': 1.15,  # Exponential backoff using this rate, -b.
        'max_delay': 10.0,  # Max possible polling interval, -m.
        'scheduler_interval': 1,  # Check schedule every second, -s.
        'periodic': True,  # Enable crontab feature.
        'check_worker_health': True,  # Enable worker health checks.
        'health_check_interval': 1,  # Check worker health every second.
    },
}
```

Custom Class used in `settings.py`:

```python
from huey.api import RedisHuey
from huey.storage import RedisStorage
from rediscluster import RedisCluster

class CustomRedisStorage(RedisStorage):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        cluster_endpoint = [{"host": "custom-data-store", "port": "6379"}]
        self.conn = RedisCluster(startup_nodes=cluster_endpoint, decode_responses=True)

class CustomRedisHuey(RedisHuey):
    storage_class = CustomRedisStorage

```

Is there anything else other than `self.conn` I need to override?

Here's the traceback on what's failing:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/huey/consumer.py", line 144, in loop
    task_list = self.huey.read_schedule(now)
  File "/usr/local/lib/python3.6/site-packages/huey/api.py", line 517, in read_schedule
    for task in self.storage.read_schedule(timestamp)]
  File "/usr/local/lib/python3.6/site-packages/huey/storage.py", line 448, in read_schedule
    tasks = self._pop(keys=[self.schedule_key], args=[unix_ts])
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 3498, in __call__
    return client.evalsha(self.sha, len(keys), *args)
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 2704, in evalsha
    return self.execute_command('EVALSHA', sha, numkeys, *keys_and_args)
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 755, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 768, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 638, in read_response
    raise response
redis.exceptions.ResponseError: MOVED 11078 10.0.4.6:6379
```

**Comment by coleifer** [comment]
I have no idea about redis cluster or that driver, which is not officially supported.

Try asking on their tracker or on stackoverflow.

**Comment by SanketDG** [comment]
It is mentioned in the official documentation, something you could take a look at:

https://redis.io/topics/cluster-tutorial#playing-with-the-cluster
