### ISSUE TITLE
Issue when running docker image from GitHub Packages - Django Application

### ISSUE THREAD

**Issue by DgRosa** [coleifer/huey#522]
I'm getting this error only when I run the docker image (with docker-compose) from my repository packages, when I copy by hand the same docker configuration and run docker-compose up it works. The error happens just by importing it, also happens on an __init__ file so it makes sense. Can someone help me please?
Here is the full stack:
```
[2020-05-22 13:30:14 +0000] [19] [ERROR] Exception in worker process
web_1    | Traceback (most recent call last):
web_1    |   File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
web_1    |     worker.init_process()
web_1    |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 119, in init_process
web_1    |     self.load_wsgi()
web_1    |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
web_1    |     self.wsgi = self.app.wsgi()
web_1    |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
web_1    |     self.callable = self.load()
web_1    |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
web_1    |     return self.load_wsgiapp()
web_1    |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
web_1    |     return util.import_app(self.app_uri)
web_1    |   File "/usr/local/lib/python3.8/site-packages/gunicorn/util.py", line 358, in import_app
web_1    |     mod = importlib.import_module(module)
web_1    |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
web_1    |     return _bootstrap._gcd_import(name[level:], package, level)
web_1    |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
web_1    |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
web_1    |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
web_1    |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
web_1    |   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
web_1    |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
web_1    |   File "/home/app/web/likacrm/wsgi.py", line 16, in <module>
web_1    |     application = get_wsgi_application()
web_1    |   File "/usr/local/lib/python3.8/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
web_1    |     django.setup(set_prefix=False)
web_1    |   File "/usr/local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
web_1    |     apps.populate(settings.INSTALLED_APPS)
web_1    |   File "/usr/local/lib/python3.8/site-packages/django/apps/registry.py", line 91, in populate
web_1    |     app_config = AppConfig.create(entry)
web_1    |   File "/usr/local/lib/python3.8/site-packages/django/apps/config.py", line 90, in create
web_1    |     module = import_module(entry)
web_1    |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
web_1    |     return _bootstrap._gcd_import(name[level:], package, level)
web_1    |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
web_1    |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
web_1    |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
web_1    |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
web_1    |   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
web_1    |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
web_1    |   File "/usr/local/lib/python3.8/site-packages/huey/contrib/djhuey/__init__.py", line 100, in <module>
web_1    |     HUEY = backend_cls(name, **huey_config)
web_1    |   File "/usr/local/lib/python3.8/site-packages/huey/api.py", line 112, in __init__
web_1    |     self.storage = self.create_storage()
web_1    |   File "/usr/local/lib/python3.8/site-packages/huey/api.py", line 130, in create_storage
web_1    |     return self.get_storage(**self.storage_kwargs)
web_1    |   File "/usr/local/lib/python3.8/site-packages/huey/api.py", line 142, in get_storage
web_1    |     return Storage(self.name, **kwargs)
web_1    |   File "/usr/local/lib/python3.8/site-packages/huey/storage.py", line 396, in __init__
web_1    |     self.name = self.clean_name(name)
web_1    |   File "/usr/local/lib/python3.8/site-packages/huey/storage.py", line 409, in clean_name
web_1    |     return re.sub('[^a-z0-9]', '', name)
web_1    |   File "/usr/local/lib/python3.8/re.py", line 210, in sub
web_1    |     return _compile(pattern, flags).sub(repl, string, count)
web_1    | TypeError: expected string or bytes-like object
```

**Comment by coleifer** [comment]
```
web_1    |     self.name = self.clean_name(name)
```

I'm guessing `name` is coming through as `None`.

**Comment by coleifer** [comment]
Please note the issue tracker is for issues, not for debugging tracebacks in your code. Those kinds of questions belong on StackOverflow.

**Comment by DgRosa** [comment]
Do you have any clue to why?

**Comment by coleifer** [comment]
The fix is quite simple:

```python
# settings.py
HUEY = {
    'name': 'my-app',
    ...
}
```

**Comment by coleifer** [comment]
The docs are also quite clear: https://huey.readthedocs.io/en/latest/contrib.html#django

**Comment by DgRosa** [comment]
@coleifer it's working now, thank you for the help, being used this lib for a long time, it's awesome :D!
