### ISSUE TITLE
SQLite locking error under WSL

### ISSUE THREAD

**Issue by johndoe46** [coleifer/huey#535]
Hello,

It seems to be a common problem for applications running under Windows Subsystem for Linux. You may not want to support it but I thought I'd report the issue anyway for info. So OS is Debian with stock python, under WSL2.:
```
Traceback (most recent call last):
  File "/home/user/venvs/circe/lib/python3.7/site-packages/huey/api.py", line 771, in schedule
    return self.huey.enqueue(task)
  File "/home/user/venvs/circe/lib/python3.7/site-packages/huey/api.py", line 283, in enqueue
    self.storage.enqueue(self.serialize_task(task), task.priority)
  File "/home/user/venvs/circe/lib/python3.7/site-packages/huey/storage.py", line 713, in enqueue
    (self.name, to_blob(data), priority or 0), commit=True)
  File "/home/user/venvs/circe/lib/python3.7/site-packages/huey/storage.py", line 668, in sql
    with self.db(commit=commit) as curs:
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/user/venvs/circe/lib/python3.7/site-packages/huey/storage.py", line 646, in db
    conn = self.conn
  File "/home/user/venvs/circe/lib/python3.7/site-packages/huey/storage.py", line 638, in conn
    self._state.set_connection(self._create_connection())
  File "/home/user/venvs/circe/lib/python3.7/site-packages/huey/storage.py", line 705, in _create_connection
    conn.execute('pragma journal_mode="%s"' % self._journal_mode)
sqlite3.OperationalError: locking protocol
```

**Comment by coleifer** [comment]
This error is coming from the underlying sqlite3 library, as opposed to the python driver or huey. It's possible that changing the journaling mode may help -- it's worth a try, anyways. Thanks for the report, nothing to do here though.
