### ISSUE TITLE
Huey Consumer and Redis exceptions

### ISSUE THREAD

**Issue by minyoung90** [coleifer/huey#540]
```
[2020-07-22 17:34:20,835] ERROR:huey.consumer.Scheduler:Scheduler:Error reading schedule.
Traceback (most recent call last):
  File "C:\xxx\venv\lib\site-packages\huey\consumer.py", line 158, in loop
    task_list = self.huey.read_schedule(now)
  File "C:\xxx\venv\lib\site-packages\huey\api.py", line 533, in read_schedule
    for task in self.storage.read_schedule(timestamp)]
  File "C:\xxx\venv\lib\site-packages\huey\storage.py", line 450, in read_schedule
    tasks = self._pop(keys=[self.schedule_key], args=[unix_ts])
  File "C:\xxx\venv\lib\site-packages\redis\client.py", line 4073, in __call__
    return client.evalsha(self.sha, len(keys), *args)
  File "C:\xxx\venv\lib\site-packages\redis\client.py", line 3143, in evalsha
    return self.execute_command('EVALSHA', sha, numkeys, *keys_and_args)
  File "C:\xxx\venv\lib\site-packages\redis\client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "C:\xxx\venv\lib\site-packages\redis\client.py", line 915, in parse_response
    response = connection.read_response()
  File "C:\xxx\venv\lib\site-packages\redis\connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: Error running script (call to xxxxxxxxx): @user_script:4: @user_script: 4: -READONLY You can't write against a read only slave.
[2020-07-22 17:34:21,163] ERROR:huey.consumer.Worker:Worker-1:Error reading from queue
Traceback (most recent call last):
  File "C:\xxx\venv\lib\site-packages\huey\consumer.py", line 108, in loop
    task = self.huey.dequeue()
  File "C:\xxx\venv\lib\site-packages\huey\api.py", line 299, in dequeue
    data = self.storage.dequeue()
  File "C:\xxx\venv\lib\site-packages\huey\storage.py", line 425, in dequeue
    timeout=self.read_timeout)[1]
  File "C:\xxx\venv\lib\site-packages\redis\client.py", line 1917, in brpop
    return self.execute_command('BRPOP', *keys)
  File "C:\xxx\venv\lib\site-packages\redis\client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "C:\xxx\venv\lib\site-packages\redis\client.py", line 915, in parse_response
    response = connection.read_response()
  File "C:\xxx\venv\lib\site-packages\redis\connection.py", line 756, in read_response
    raise response
redis.exceptions.ReadOnlyError: You can't write against a read only slave.
```

I am testing a server with Huey 24 hours.
The above exception occurred **several times** while resting period (No tasks were called).
But, Huey is running fine (even the above exception, I could call tasks)

```
Python 3.6.8
Django 2.2.8
hue 2.2.0
redis 3.5.3

HUEY = {
    'huey_class': 'huey.RedisHuey',  # Huey implementation to use.
    'name': 'rpa-prod-task-queue',  # Use db name for huey.
    'results': True,  # Store return values of tasks.
    'store_none': False,  # If a task returns None, do not save to results.
    'immediate': DEBUG,  # If DEBUG=True, run synchronously.
    'utc': True,  # Use UTC for all times internally.
    'blocking': True,  # Perform blocking pop rather than poll Redis.
    'connection': {
        'host': 'localhost',
        'port': 6379,
        'db': 0,
        'connection_pool': None,  # Definitely you should use pooling!
        # ... tons of other options, see redis-py for details.

        # huey-specific connection parameters.
        'read_timeout': 1,  # If not polling (blocking pop), use timeout.
        'url': None,  # Allow Redis config via a DSN.
    },
    'consumer': {
        'workers': 1,
        'worker_type': 'thread',
        'initial_delay': 0.1,  # Smallest polling interval, same as -d.
        'backoff': 1.15,  # Exponential backoff using this rate, -b.
        'max_delay': 10.0,  # Max possible polling interval, -m.
        'scheduler_interval': 1,  # Check schedule every second, -s.
        'periodic': True,  # Enable crontab feature.
        'check_worker_health': True,  # Enable worker health checks.
        'health_check_interval': 1,  # Check worker health every second.
    },
}
```

**Comment by coleifer** [comment]
It's quite clear:

redis.exceptions.ResponseError: Error running script (call to xxxxxxxxx): @user_script:4: @user_script: 4: -READONLY You can't write against a read only slave.

>You can't write against a read only slave.

**Comment by minyoung90** [comment]
@coleifer So, Can I ignore this error?

**Comment by coleifer** [comment]
That error is something being reported by your redis server and I have no idea about your setup, whether you're using replication, etc, etc, but I'm quite convinced the problem is on your end rather than with huey.
