### ISSUE TITLE
django-huey returning empty querysets while performing queries on django models.

### ISSUE THREAD

**Issue by vaibhavmano** [coleifer/huey#542]
```
@db_task()
def test_db_access(tenant_id, batch_obj):
    print('DBAccess')
    print(tenant_id)
    print(batch_obj.id)
    files = File.objects.filter(batch_id=batch_obj.id)
    print(files)
```
If I don't use django huey, I'm getting the proper queryset but if I start using huey, it keeps returning empty querysets for all models. Only the 'DBAccess', tenant_id and batch_obj.id is getting printed but files is always '[]' . 
This is the settings for huey in my settings.py
```
HUEY = {
    'huey_class': 'huey.RedisHuey',  # Huey implementation to use.
    'name': DATABASES['default']['NAME'],
    'consumer': {
        'workers': 4, 
        'worker_type': 'thread'
    },
    'immediate': False,
    'connection': {
        'host': RedisConfig.HOST,
        'port': RedisConfig.PORT,
    },
}
```

Actual log in terminal (Without huey)
```
DBAccess
2f0f853d-a275-4ec8-a6bf-94aa1a683c8e
1
<QuerySet [<File: File object (1)>, <File: File object (2)>]>

```

Log in terminal (Using huey)
```
+ textract.api_views.batch.batch_process.test_db_access
[2020-07-29 17:43:58,394] INFO:huey:Worker-1:Executing textract.api_views.batch.batch_process.test_db_access: e28d777b-d4b2-4b53-9fde-655e3ae0cbf9
DBAccess
2f0f853d-a275-4ec8-a6bf-94aa1a683c8e
1
<QuerySet []>
``` 

So I tried objects.get instead of filter and I get this error only while using huey.
```
[2020-07-29 19:35:27,945] ERROR:huey:Worker-1:Unhandled exception in task a4ade625-b892-4029-aa71-310c39fa5ba2.
Traceback (most recent call last):
  File "/home/vyakya2/Desktop/textract-table/venv/lib/python3.7/site-packages/huey/api.py", line 359, in _execute
    task_value = task.execute()
  File "/home/vyakya2/Desktop/textract-table/venv/lib/python3.7/site-packages/huey/api.py", line 723, in execute
    return func(*args, **kwargs)
  File "/home/vyakya2/Desktop/textract-table/venv/lib/python3.7/site-packages/huey/contrib/djhuey/__init__.py", line 132, in inner
    return fn(*args, **kwargs)
  File "/home/vyakya2/Desktop/textract-table/kyc_detection/textract/api_views/batch/batch_process.py", line 28, in test_db_access
    files = Batch.objects.get(id=batch_obj.id)
  File "/home/vyakya2/Desktop/textract-table/venv/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vyakya2/Desktop/textract-table/venv/lib/python3.7/site-packages/django/db/models/query.py", line 417, in get
    self.model._meta.object_name
textract.models.models.Batch.DoesNotExist: Batch matching query does not exist.

```

**Comment by coleifer** [comment]
You may be firing off your task before the db rows/transaction is committed.

**Comment by vaibhavmano** [comment]
The row/transaction is already existing and I'm just querying but that doesn't seem to work. I'm also using multiple databases in postgres. Could it be because of that?

**Comment by coleifer** [comment]
I don't know, but huey is not *fundamentally broken* as your issue would suggest, so I'm inclined to think it's on your side.

**Comment by vaibhavmano** [comment]
Yeah, it is not broken but there's an issue when running multiple databases. huey doesn't seem to use the default database and I had to specifically mention which database with the keyword '_using_'. Got it sorted.
