### ISSUE TITLE
pickle error trying to launch huey_consumer on windows

### ISSUE THREAD

**Issue by Berserker66** [coleifer/huey#551]
Tried running the in executable consumer
this is WebHostLib.tasking.huey:
```
from huey import SqliteHuey


huey = SqliteHuey()
```
and this is what I get:
```
huey_consumer.exe WebHostLib.tasking.huey --logfile="test.log" -w 4 -k process
Traceback (most recent call last):
  File "C:\Program Files\Python38\Scripts\huey_consumer-script.py", line 33, in <module>
    sys.exit(load_entry_point('huey==2.3.0', 'console_scripts', 'huey_consumer')())
  File "C:\Program Files\Python38\lib\site-packages\huey\bin\huey_consumer.py", line 51, in consumer_main
    consumer.run()
  File "C:\Program Files\Python38\lib\site-packages\huey\consumer.py", line 421, in run
    self.start()
  File "C:\Program Files\Python38\lib\site-packages\huey\consumer.py", line 390, in start
    self.scheduler.start()
  File "C:\Program Files\Python38\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Program Files\Python38\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Program Files\Python38\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Program Files\Python38\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Program Files\Python38\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'Consumer._create_process.<locals>._run'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\Python38\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Program Files\Python38\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
```

**Comment by dolamroth** [comment]
Huey's Consumer._create_process.<locals>._run creates instance of "Worker", to which a link to parent "Huey" object is passed. There is a somewhat recursive linkage, which is fine on Linux due to shared memory in fork system call. This is impossible in spawn on Windows and causes a Permission error. 

Apparently, with current architecture of the library, it is impossible to run it on Windows in process mode. Try using celery with strategy 2 from here (haven't tested it yet, though): https://www.distributedpython.com/2018/08/21/celery-4-windows/

**Comment by coleifer** [comment]
I cannot endorse those suggestions or any of these hacks. Better to run in threaded mode if you have to develop on windows.

**Comment by trepca** [comment]
Getting the same issue on OS X 12.6 (21G115), M1 Mac, Python 3.10 when running in process mode.
