### ISSUE TITLE
CI pipeline? (`python setup.py test` fails on 3.4, 3.7, 3.9)

### ISSUE THREAD

**Issue by thebjorn** [coleifer/huey#566]
The build button on the home page in Github says unknown and doesn't go anywhere when clicked on.

I followed the instructions on https://huey.readthedocs.io/en/latest/installation.html

```
$ git clone https://github.com/coleifer/huey.git
$ cd huey
$ python setup.py install
$ python setup.py test
```

and all of Pythons 3.4, 3.7, 3.9 gave the same result:

```
(dev35) go|c:\srv\tmp\huey> python setup.py test
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
running egg_info
writing huey.egg-info\PKG-INFO
writing requirements to huey.egg-info\requires.txt
writing top-level names to huey.egg-info\top_level.txt
writing dependency_links to huey.egg-info\dependency_links.txt
writing entry points to huey.egg-info\entry_points.txt
reading manifest file 'huey.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'huey.egg-info\SOURCES.txt'
running build_ext
error: [WinError 2] The system cannot find the file specified
```

If I change line 20 in test_kt_huey.py to `has_ktserver = False` the tests run, with 11 errors. Is this expected?

Testrun after above change:
```
(dev35) go|c:\srv\tmp\huey> python setup.py test
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
running egg_info
writing dependency_links to huey.egg-info\dependency_links.txt
writing requirements to huey.egg-info\requires.txt
writing top-level names to huey.egg-info\top_level.txt
writing entry points to huey.egg-info\entry_points.txt
writing huey.egg-info\PKG-INFO
reading manifest file 'huey.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'huey.egg-info\SOURCES.txt'
running build_ext
test_consumer_config (huey.tests.test_consumer.TestConsumerConfig) ... ok
test_default_config (huey.tests.test_consumer.TestConsumerConfig) ... ok
test_invalid_values (huey.tests.test_consumer.TestConsumerConfig) ... ok
test_consumer_minimal (huey.tests.test_consumer.TestConsumerIntegration) ... ok
test_consumer_periodic_tasks (huey.tests.test_consumer.TestConsumerIntegration) ... ok
test_consumer_schedule_task (huey.tests.test_consumer.TestConsumerIntegration) ... ok
test_crontab_all_together (huey.tests.test_crontab.TestCrontab) ... ok
test_crontab_day (huey.tests.test_crontab.TestCrontab) ... ok
test_crontab_day_of_week (huey.tests.test_crontab.TestCrontab) ... ok
test_crontab_hour (huey.tests.test_crontab.TestCrontab) ... ok
test_crontab_minute (huey.tests.test_crontab.TestCrontab) ... ok
test_crontab_month (huey.tests.test_crontab.TestCrontab) ... ok
test_crontab_sunday (huey.tests.test_crontab.TestCrontab) ... ok
test_invalid_crontabs (huey.tests.test_crontab.TestCrontab) ... ok
test_call_periodic_task (huey.tests.test_api.TestDecorators) ... ok
test_context_task (huey.tests.test_api.TestDecorators) ... ok
test_dynamic_periodic_tasks (huey.tests.test_api.TestDecorators) ... ok
test_periodic_task (huey.tests.test_api.TestDecorators) ... ok
test_task_decorator (huey.tests.test_api.TestDecorators) ... ok
test_task_parameters (huey.tests.test_api.TestDecorators) ... ok
test_disable_result_store (huey.tests.test_api.TestDisableResultStore) ... ok
test_docstring_preserved (huey.tests.test_api.TestDocstring) ... ok
test_consumer_integration (huey.tests.test_storage.TestFileStorageMethods) ... ERROR
test_filesystem_result_store (huey.tests.test_storage.TestFileStorageMethods) ... ok
test_fs_multithreaded (huey.tests.test_storage.TestFileStorageMethods) ... Exception in thread Thread-11:
Traceback (most recent call last):
  File "c:\PROGRA~2\Python35-32\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "c:\PROGRA~2\Python35-32\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "c:\srv\tmp\huey\huey\tests\test_storage.py", line 344, in dequeue_tasks
    data = self.huey.storage.dequeue()
  File "c:\srv\tmp\huey\huey\storage.py", line 921, in dequeue
    os.unlink(tmp_dest)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: '/tmp/test-huey-storage\\queue\\ffff-01766cf4220b.tmp'

Exception in thread Thread-12:
Traceback (most recent call last):
  File "c:\PROGRA~2\Python35-32\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "c:\PROGRA~2\Python35-32\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "c:\srv\tmp\huey\huey\tests\test_storage.py", line 344, in dequeue_tasks
    data = self.huey.storage.dequeue()
  File "c:\srv\tmp\huey\huey\storage.py", line 921, in dequeue
    os.unlink(tmp_dest)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: '/tmp/test-huey-storage\\queue\\ffff-01766cf4220c.tmp'

Exception in thread Thread-13:
Traceback (most recent call last):
  File "c:\PROGRA~2\Python35-32\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "c:\PROGRA~2\Python35-32\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "c:\srv\tmp\huey\huey\tests\test_storage.py", line 344, in dequeue_tasks
    data = self.huey.storage.dequeue()
  File "c:\srv\tmp\huey\huey\storage.py", line 921, in dequeue
    os.unlink(tmp_dest)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: '/tmp/test-huey-storage\\queue\\ffff-01766cf4220d.tmp'

Exception in thread Thread-14:
Traceback (most recent call last):
  File "c:\PROGRA~2\Python35-32\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "c:\PROGRA~2\Python35-32\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "c:\srv\tmp\huey\huey\tests\test_storage.py", line 344, in dequeue_tasks
    data = self.huey.storage.dequeue()
  File "c:\srv\tmp\huey\huey\storage.py", line 921, in dequeue
    os.unlink(tmp_dest)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: '/tmp/test-huey-storage\\queue\\ffff-01766cf4220d.001.tmp'

Exception in thread Thread-15:
Traceback (most recent call last):
  File "c:\PROGRA~2\Python35-32\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "c:\PROGRA~2\Python35-32\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "c:\srv\tmp\huey\huey\tests\test_storage.py", line 344, in dequeue_tasks
    data = self.huey.storage.dequeue()
  File "c:\srv\tmp\huey\huey\storage.py", line 921, in dequeue
    os.unlink(tmp_dest)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: '/tmp/test-huey-storage\\queue\\ffff-01766cf4220f.tmp'

Exception in thread Thread-16:
Traceback (most recent call last):
  File "c:\PROGRA~2\Python35-32\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "c:\PROGRA~2\Python35-32\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "c:\srv\tmp\huey\huey\tests\test_storage.py", line 344, in dequeue_tasks
    data = self.huey.storage.dequeue()
  File "c:\srv\tmp\huey\huey\storage.py", line 921, in dequeue
    os.unlink(tmp_dest)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: '/tmp/test-huey-storage\\queue\\ffff-01766cf42210.tmp'

Exception in thread Thread-17:
Traceback (most recent call last):
  File "c:\PROGRA~2\Python35-32\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "c:\PROGRA~2\Python35-32\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "c:\srv\tmp\huey\huey\tests\test_storage.py", line 344, in dequeue_tasks
    data = self.huey.storage.dequeue()
  File "c:\srv\tmp\huey\huey\storage.py", line 921, in dequeue
    os.unlink(tmp_dest)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: '/tmp/test-huey-storage\\queue\\ffff-01766cf42210.001.tmp'

Exception in thread Thread-18:
Traceback (most recent call last):
  File "c:\PROGRA~2\Python35-32\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "c:\PROGRA~2\Python35-32\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "c:\srv\tmp\huey\huey\tests\test_storage.py", line 344, in dequeue_tasks
    data = self.huey.storage.dequeue()
  File "c:\srv\tmp\huey\huey\storage.py", line 921, in dequeue
    os.unlink(tmp_dest)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: '/tmp/test-huey-storage\\queue\\ffff-01766cf42211.tmp'

Exception in thread Thread-19:
Traceback (most recent call last):
  File "c:\PROGRA~2\Python35-32\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "c:\PROGRA~2\Python35-32\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "c:\srv\tmp\huey\huey\tests\test_storage.py", line 344, in dequeue_tasks
    data = self.huey.storage.dequeue()
  File "c:\srv\tmp\huey\huey\storage.py", line 921, in dequeue
    os.unlink(tmp_dest)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: '/tmp/test-huey-storage\\queue\\ffff-01766cf42211.001.tmp'

Exception in thread Thread-20:
Traceback (most recent call last):
  File "c:\PROGRA~2\Python35-32\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "c:\PROGRA~2\Python35-32\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "c:\srv\tmp\huey\huey\tests\test_storage.py", line 344, in dequeue_tasks
    data = self.huey.storage.dequeue()
  File "c:\srv\tmp\huey\huey\storage.py", line 921, in dequeue
    os.unlink(tmp_dest)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: '/tmp/test-huey-storage\\queue\\ffff-01766cf42212.tmp'

FAIL
test_priority (huey.tests.test_storage.TestFileStorageMethods) ... ERROR
test_queue_methods (huey.tests.test_storage.TestFileStorageMethods) ... ERROR
test_result_store_methods (huey.tests.test_storage.TestFileStorageMethods) ... ok
test_schedule_methods (huey.tests.test_storage.TestFileStorageMethods) ... ERROR
test_flush_locks (huey.tests.test_api.TestHueyAPIs) ... ok
test_put_get (huey.tests.test_api.TestHueyAPIs) ... ok
test_serialize_deserialize (huey.tests.test_api.TestHueyAPIs) ... ok
test_serialize_deserialize_signed (huey.tests.test_api.TestHueyAPIs) ... ok
test_unsupported (huey.tests.test_api.TestHueyAPIs) ... ok
test_immediate (huey.tests.test_immediate.TestImmediate) ... ok
test_immediate_pipeline (huey.tests.test_immediate.TestImmediate) ... ok
test_immediate_reschedule (huey.tests.test_immediate.TestImmediate) ... ok
test_immediate_revoke_restore (huey.tests.test_immediate.TestImmediate) ... ok
test_immediate_scheduling (huey.tests.test_immediate.TestImmediate) ... ok
test_map (huey.tests.test_immediate.TestImmediate) ... ok
test_swap_immediate (huey.tests.test_immediate.TestImmediate) ... ok
test_immediate_real_storage (huey.tests.test_immediate.TestImmediateMemoryStorage) ... ok
test_immediate_storage (huey.tests.test_immediate.TestImmediateMemoryStorage) ... ok
test_consumer_integration (huey.tests.test_kt_huey.TestKyotoTycoonHuey) ... skipped 'requires ukt'
test_expire_results (huey.tests.test_kt_huey.TestKyotoTycoonHuey) ... skipped 'requires ukt'
test_priority (huey.tests.test_kt_huey.TestKyotoTycoonHuey) ... skipped 'requires ukt'
test_queue_methods (huey.tests.test_kt_huey.TestKyotoTycoonHuey) ... skipped 'requires ukt'
test_result_store_methods (huey.tests.test_kt_huey.TestKyotoTycoonHuey) ... skipped 'requires ukt'
test_schedule_methods (huey.tests.test_kt_huey.TestKyotoTycoonHuey) ... skipped 'requires ukt'
test_consumer_integration (huey.tests.test_storage.TestMemoryStorage) ... ok
test_priority (huey.tests.test_storage.TestMemoryStorage) ... ok
test_queue_methods (huey.tests.test_storage.TestMemoryStorage) ... ok
test_result_store_methods (huey.tests.test_storage.TestMemoryStorage) ... ok
test_schedule_methods (huey.tests.test_storage.TestMemoryStorage) ... ok
test_multiple_huey (huey.tests.test_api.TestMultipleHuey) ... ok
test_normalize_time (huey.tests.test_utils.TestNormalizeTime) ... ERROR
test_periodic_priority (huey.tests.test_priority.TestPriority) ... ok
test_priority_override (huey.tests.test_priority.TestPriority) ... ok
test_priority_retry (huey.tests.test_priority.TestPriority) ... ok
test_priority_simple (huey.tests.test_priority.TestPriority) ... ok
test_schedule_priority (huey.tests.test_priority.TestPriority) ... ok
test_conflicting_init_args (huey.tests.test_storage.TestPriorityRedisStorage) ... ok
test_consumer_integration (huey.tests.test_storage.TestPriorityRedisStorage) ... ok
test_priority (huey.tests.test_storage.TestPriorityRedisStorage) ... ok
test_queue_methods (huey.tests.test_storage.TestPriorityRedisStorage) ... ok
test_result_store_methods (huey.tests.test_storage.TestPriorityRedisStorage) ... ok
test_schedule_methods (huey.tests.test_storage.TestPriorityRedisStorage) ... ok
test_conflicting_init_args (huey.tests.test_storage.TestPriorityRedisStorageNotBlocking) ... ok
test_consumer_integration (huey.tests.test_storage.TestPriorityRedisStorageNotBlocking) ... ok
test_priority (huey.tests.test_storage.TestPriorityRedisStorageNotBlocking) ... ok
test_queue_methods (huey.tests.test_storage.TestPriorityRedisStorageNotBlocking) ... ok
test_result_store_methods (huey.tests.test_storage.TestPriorityRedisStorageNotBlocking) ... ok
test_schedule_methods (huey.tests.test_storage.TestPriorityRedisStorageNotBlocking) ... ok
test_read_periodic (huey.tests.test_api.TestQueue) ... ok
test_read_schedule (huey.tests.test_api.TestQueue) ... ok
test_reschedule (huey.tests.test_api.TestQueue) ... ok
test_reschedule_no_delay (huey.tests.test_api.TestQueue) ... ok
test_result_store (huey.tests.test_api.TestQueue) ... ok
test_retry (huey.tests.test_api.TestQueue) ... ok
test_retry_delay (huey.tests.test_api.TestQueue) ... ok
test_retry_delay_periodic (huey.tests.test_api.TestQueue) ... ok
test_retry_periodic (huey.tests.test_api.TestQueue) ... ok
test_retry_to_success (huey.tests.test_api.TestQueue) ... ok
test_retrytask_explicit (huey.tests.test_api.TestQueue) ... ok
test_revoke_by_id (huey.tests.test_api.TestQueue) ... ok
test_revoke_once (huey.tests.test_api.TestQueue) ... ok
test_revoke_periodic (huey.tests.test_api.TestQueue) ... ok
test_revoke_task (huey.tests.test_api.TestQueue) ... ok
test_revoke_task_instance (huey.tests.test_api.TestQueue) ... ok
test_revoke_task_instance_persistent (huey.tests.test_api.TestQueue) ... ok
test_revoke_until (huey.tests.test_api.TestQueue) ... ok
test_scheduling (huey.tests.test_api.TestQueue) ... ok
test_subtask_error (huey.tests.test_api.TestQueue) ... ok
test_task_error (huey.tests.test_api.TestQueue) ... ok
test_workflow (huey.tests.test_api.TestQueue) ... ok
test_consumer_integration (huey.tests.test_storage.TestRedisExpireStorage) ... ok
test_expire_results (huey.tests.test_storage.TestRedisExpireStorage) ... ok
test_integration_2 (huey.tests.test_storage.TestRedisExpireStorage) ... ok
test_priority (huey.tests.test_storage.TestRedisExpireStorage) ... skipped 'priority support required'
test_queue_methods (huey.tests.test_storage.TestRedisExpireStorage) ... ok
test_result_store_methods (huey.tests.test_storage.TestRedisExpireStorage) ... ok
test_schedule_methods (huey.tests.test_storage.TestRedisExpireStorage) ... ok
test_conflicting_init_args (huey.tests.test_storage.TestRedisStorage) ... ok
test_consumer_integration (huey.tests.test_storage.TestRedisStorage) ... ok
test_priority (huey.tests.test_storage.TestRedisStorage) ... skipped 'priority support required'
test_queue_methods (huey.tests.test_storage.TestRedisStorage) ... ok
test_result_store_methods (huey.tests.test_storage.TestRedisStorage) ... ok
test_schedule_methods (huey.tests.test_storage.TestRedisStorage) ... ok
test_huey1_compat (huey.tests.test_registry.TestRegistry) ... ok
test_message_wrapping (huey.tests.test_registry.TestRegistry) ... ok
test_missing_task (huey.tests.test_registry.TestRegistry) ... ok
test_periodic_tasks (huey.tests.test_registry.TestRegistry) ... ok
test_register_unique (huey.tests.test_registry.TestRegistry) ... ok
test_register_unregister (huey.tests.test_registry.TestRegistry) ... ok
test_wrap_exception (huey.tests.test_utils.TestReraiseAs) ... ok
test_mismatched_compression (huey.tests.test_serializer.TestSerializer) ... ok
test_serializer (huey.tests.test_serializer.TestSerializer) ... ok
test_serializer_gzip (huey.tests.test_serializer.TestSerializer) ... ok
test_serializer_zlib (huey.tests.test_serializer.TestSerializer) ... ok
test_multi_handlers (huey.tests.test_signals.TestSignals) ... ok
test_signal_complete_result_ready (huey.tests.test_signals.TestSignals) ... ok
test_signals_locked (huey.tests.test_signals.TestSignals) ... ok
test_signals_on_retry (huey.tests.test_signals.TestSignals) ... ok
test_signals_revoked (huey.tests.test_signals.TestSignals) ... ok
test_signals_simple (huey.tests.test_signals.TestSignals) ... ok
test_specific_handler (huey.tests.test_signals.TestSignals) ... ok
test_consumer_integration (huey.tests.test_sql_huey.TestSqlStorage) ... skipped 'requires peewee'
test_priority (huey.tests.test_sql_huey.TestSqlStorage) ... skipped 'requires peewee'
test_queue_methods (huey.tests.test_sql_huey.TestSqlStorage) ... skipped 'requires peewee'
test_result_store_methods (huey.tests.test_sql_huey.TestSqlStorage) ... skipped 'requires peewee'
test_schedule_methods (huey.tests.test_sql_huey.TestSqlStorage) ... skipped 'requires peewee'
test_sql_huey_basic (huey.tests.test_sql_huey.TestSqlStorage) ... skipped 'requires peewee'
test_sql_huey_priority (huey.tests.test_sql_huey.TestSqlStorage) ... skipped 'requires peewee'
test_consumer_integration (huey.tests.test_storage.TestSqliteStorage) ... ERROR
test_priority (huey.tests.test_storage.TestSqliteStorage) ... ERROR
test_queue_methods (huey.tests.test_storage.TestSqliteStorage) ... ERROR
test_result_store_methods (huey.tests.test_storage.TestSqliteStorage) ... ERROR
test_schedule_methods (huey.tests.test_storage.TestSqliteStorage) ... ERROR
test_timeout (huey.tests.test_storage.TestSqliteStorage) ... ERROR
test_storage_wrappers (huey.tests.test_api.TestStorageWrappers) ... ok
test_chain_errors (huey.tests.test_api.TestTaskChaining) ... ok
test_error_callback (huey.tests.test_api.TestTaskChaining) ... ok
test_mixed_tasks_instances (huey.tests.test_api.TestTaskChaining) ... ok
test_partial (huey.tests.test_api.TestTaskChaining) ... ok
test_pipeline_dict (huey.tests.test_api.TestTaskChaining) ... ok
test_pipeline_error_midway (huey.tests.test_api.TestTaskChaining) ... ok
test_pipeline_revoke_midway (huey.tests.test_api.TestTaskChaining) ... ok
test_pipeline_tuple (huey.tests.test_api.TestTaskChaining) ... ok
test_task_instances_args_kwargs (huey.tests.test_api.TestTaskChaining) ... ok
test_hook_unregister (huey.tests.test_api.TestTaskHooks) ... ok
test_task_hook_errors (huey.tests.test_api.TestTaskHooks) ... ok
test_task_hooks (huey.tests.test_api.TestTaskHooks) ... ok
test_task_locking (huey.tests.test_api.TestTaskLocking) ... ok
test_fake_wrapper (huey.tests.test_wrappers.TestWrappers) ... ok
test_wrappers (huey.tests.test_wrappers.TestWrappers) ... ok

======================================================================
ERROR: test_consumer_integration (huey.tests.test_storage.TestFileStorageMethods)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\srv\tmp\huey\huey\tests\test_storage.py", line 383, in test_consumer_integration
    return super(TestFileStorageMethods, self).test_consumer_integration()
  File "c:\srv\tmp\huey\huey\tests\test_storage.py", line 154, in test_consumer_integration
    self.assertEqual(r1.get(blocking=True, timeout=5), 2)
  File "c:\srv\tmp\huey\huey\api.py", line 897, in get
    revoke_on_timeout, preserve)
  File "c:\srv\tmp\huey\huey\api.py", line 885, in get_raw_result
    raise HueyException('timed out waiting for result')
huey.exceptions.HueyException: timed out waiting for result

======================================================================
ERROR: test_priority (huey.tests.test_storage.TestFileStorageMethods)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\srv\tmp\huey\huey\tests\test_storage.py", line 142, in test_priority
    self.assertEqual([self.s.dequeue() for _ in range(10)], expected)
  File "c:\srv\tmp\huey\huey\tests\test_storage.py", line 142, in <listcomp>
    self.assertEqual([self.s.dequeue() for _ in range(10)], expected)
  File "c:\srv\tmp\huey\huey\storage.py", line 921, in dequeue
    os.unlink(tmp_dest)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: '/tmp/test-huey-storage\\queue\\fff6-01766cf4239e.tmp'

======================================================================
ERROR: test_queue_methods (huey.tests.test_storage.TestFileStorageMethods)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\srv\tmp\huey\huey\tests\test_storage.py", line 49, in test_queue_methods
    self.assertEqual(self.s.dequeue(), b'item-0')
  File "c:\srv\tmp\huey\huey\storage.py", line 921, in dequeue
    os.unlink(tmp_dest)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: '/tmp/test-huey-storage\\queue\\ffff-01766cf423a4.tmp'

======================================================================
ERROR: test_schedule_methods (huey.tests.test_storage.TestFileStorageMethods)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\srv\tmp\huey\huey\tests\test_storage.py", line 78, in test_schedule_methods
    sched = self.s.read_schedule(timestamp)
  File "c:\srv\tmp\huey\huey\storage.py", line 973, in read_schedule
    os.unlink(filename)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: '/tmp/test-huey-storage\\schedule\\00dc70679e20.tmp'

======================================================================
ERROR: test_normalize_time (huey.tests.test_utils.TestNormalizeTime)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\srv\tmp\huey\huey\tests\test_utils.py", line 44, in setUp
    time.tzset()
AttributeError: module 'time' has no attribute 'tzset'

======================================================================
ERROR: test_consumer_integration (huey.tests.test_storage.TestSqliteStorage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\srv\tmp\huey\huey\tests\test_storage.py", line 278, in tearDown
    os.unlink('huey_storage.db')
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'huey_storage.db'

======================================================================
ERROR: test_priority (huey.tests.test_storage.TestSqliteStorage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\srv\tmp\huey\huey\tests\test_storage.py", line 278, in tearDown
    os.unlink('huey_storage.db')
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'huey_storage.db'

======================================================================
ERROR: test_queue_methods (huey.tests.test_storage.TestSqliteStorage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\srv\tmp\huey\huey\tests\test_storage.py", line 278, in tearDown
    os.unlink('huey_storage.db')
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'huey_storage.db'

======================================================================
ERROR: test_result_store_methods (huey.tests.test_storage.TestSqliteStorage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\srv\tmp\huey\huey\tests\test_storage.py", line 278, in tearDown
    os.unlink('huey_storage.db')
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'huey_storage.db'

======================================================================
ERROR: test_schedule_methods (huey.tests.test_storage.TestSqliteStorage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\srv\tmp\huey\huey\tests\test_storage.py", line 278, in tearDown
    os.unlink('huey_storage.db')
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'huey_storage.db'

======================================================================
ERROR: test_timeout (huey.tests.test_storage.TestSqliteStorage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\srv\tmp\huey\huey\tests\test_storage.py", line 278, in tearDown
    os.unlink('huey_storage.db')
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'huey_storage.db'

======================================================================
FAIL: test_fs_multithreaded (huey.tests.test_storage.TestFileStorageMethods)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\srv\tmp\huey\huey\tests\test_storage.py", line 373, in test_fs_multithreaded
    self.assertEqual(out_q.qsize(), nthreads * ntasks)
AssertionError: 0 != 500

----------------------------------------------------------------------
Ran 155 tests in 11.321s

FAILED (failures=1, errors=11, skipped=15)
Test failed: <unittest.runner.TextTestResult run=155 errors=11 failures=1>
error: Test failed: <unittest.runner.TextTestResult run=155 errors=11 failures=1>

(dev35) go|c:\srv\tmp\huey>
```

**Comment by coleifer** [comment]
travis-ci has reneged on their assurances they would continue to support open-source projects, and they are planning on shutting down their free stuff at the end of the month, so the CI is currently unavailable until I can get migrated to something else.

The reason the tests are failing is because you are running on windows and the test suite is designed to work on linux. I just re-ran tests and all are passing.

**Comment by thebjorn** [comment]
> travis-ci has reneged on their assurances they would continue to support open-source projects, and they are planning on shutting down their free stuff at the end of the month, so the CI is currently unavailable until I can get migrated to something else.

bastards ;-)

> I've got CI set-up for this repo using github actions and it's passing.

excellent, thank you!

> The reason the tests are failing is because you are running on windows and the test suite is designed to work on linux. I just re-ran tests and all are passing.

I had a feeling that was the case. Is huey itself expected to run on Windows (it has the `'Operating System :: OS Independent'` classifier, so I'm assuming yes..?)

**Comment by coleifer** [comment]
The threaded workers should work fine on windows, but not multiprocess.
