### ISSUE TITLE
Flask - RuntimeError: Working outside of application context.

### ISSUE THREAD

**Issue by amks1** [coleifer/huey#612]
Hi, I followed the flask example provided, but I'm getting this error.

```
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
to interface with the current application object in some way. To solve
this, set up an application context with app.app_context().  See the
documentation for more information.
```

Do I have to create an app context in each function that I need to call? Is there any way I can set it up with an app extension globally, and all discovered tasks can get the app context automatically? Because almost all my task functions could be called either locally or through the scheduler depending on various conditions.

**Comment by coleifer** [comment]
What is the full traceback?

**Comment by coleifer** [comment]
I just ran the example app locally and it works just fine - I'm able to create an account, post tweets, etc. Tested with flask 2.0.1.

**Comment by amks1** [comment]
Hi @coleifer I'm sorry that I didn't make myself clear in my post. What I meant was that I integrated huey into my Flask app following the examples, and it gave me that error. After that I experimented a lot with the code structuring. I've created a separate file to run the huey worker from:

**huey_consumer.py**
``` python3
from gevent import monkey
monkey.patch_all()

from fmc.factory_app import create_app
from huey import RedisHuey
from fmc.settings import REDIS_URI

app = create_app()
huey = RedisHuey('fmc', url=REDIS_URI)

from fmc.factory_app import *
```

For my application to run, I have 2 main files: 

**factory_utils.py**
``` python3
from flask_mail import Mail
from fmc.settings import REDIS_URI
from flask_socketio import SocketIO
from huey import RedisHuey


fmc_mail = Mail()
socketio = SocketIO()
huey = RedisHuey('fmc', url=REDIS_URI)
```

and **factory_app.py**
``` python3
from fmc.settings import *
from flask import Flask
from flask_login import LoginManager
from fmc.models import User
from fmc.async_fns import *


def create_app(app_name=__name__, **kwargs):

	app = Flask(app_name, template_folder="./templates")

	#* Huey Configuration
	from fmc.factory_utils import huey

	#* SocketIO Configuration
	from fmc.factory_utils import socketio
	socketio.init_app(app)

	#* SMTP Configuration
	from fmc.factory_utils import fmc_mail
	app.config["SECRET_KEY"] = SECRET_KEY
	app.config['MAIL_SERVER'] = SMTP_HOST
	app.config['MAIL_PORT'] = SMTP_PORT
	app.config['MAIL_USERNAME'] = SMTP_USER
	app.config['MAIL_PASSWORD'] = SMTP_PASSWORD
	app.config['MAIL_USE_TLS'] = SMTP_USE_TLS
	app.config['MAIL_USE_SSL'] = SMTP_USE_SSL
	fmc_mail.init_app(app)
	
	#* Blueprint Configuration
	# Blueprint registrations go here
	
	return app


# from celery import Celery
```

I run the huey worker using the command `huey_consumer.py services.huey.huey_consumer.huey` , and the traceback is also provided below: 

```
(.venv) C:\Users\AM\Documents\GitHub\fmc>huey_consumer.py services.huey.huey_consumer.huey 
[2021-07-20 09:39:12,278] INFO:huey.consumer:MainThread:Huey consumer started with 1 thread, PID 15424 at 2021-07-20 05:39:12.278242
[2021-07-20 09:39:12,278] INFO:huey.consumer:MainThread:Scheduler runs every 1 second(s).
[2021-07-20 09:39:12,278] INFO:huey.consumer:MainThread:Periodic tasks are enabled.
[2021-07-20 09:39:12,278] INFO:huey.consumer:MainThread:The following commands are available:
+ fmc.helpers.workbox.location_send
+ fmc.helpers.workbox.messenger_send
+ fmc.models._delete_storagebucket_folder
+ fmc.models.log
+ fmc.async_fns.mail_tester
+ fmc.helpers.smtp.send_email
+ fmc.helpers.smtp.mail_tester
[2021-07-20 09:43:57,847] INFO:huey:Worker-1:Executing fmc.helpers.smtp.mail_tester: 0002fe67-4f8a-4d0d-9a5b-191d8ed934a0
mail tester
[2021-07-20 09:43:57,856] ERROR:huey:Worker-1:Unhandled exception in task 0002fe67-4f8a-4d0d-9a5b-191d8ed934a0.
Traceback (most recent call last):
  File "c:\users\AM\documents\github\fmc\.venv\lib\site-packages\huey\api.py", line 367, in _execute
    task_value = task.execute()
  File "c:\users\AM\documents\github\fmc\.venv\lib\site-packages\huey\api.py", line 740, in execute
    return func(*args, **kwargs)
  File "C:\Users\AM\Documents\GitHub\fmc\fmc\helpers\smtp.py", line 31, in mail_tester  
    fmc_mail.send(msg)
  File "c:\users\AM\documents\github\fmc\.venv\lib\site-packages\flask_mail.py", line 491, in 
send
    with self.connect() as connection:
  File "c:\users\AM\documents\github\fmc\.venv\lib\site-packages\flask_mail.py", line 508, in 
connect
    return Connection(app.extensions['mail'])
  File "c:\users\AM\documents\github\fmc\.venv\lib\site-packages\werkzeug\local.py", line 422, in __get__
    obj = instance._get_current_object()
  File "c:\users\AM\documents\github\fmc\.venv\lib\site-packages\werkzeug\local.py", line 544, in _get_current_object
    return self.__local()  # type: ignore
  File "c:\users\AM\documents\github\fmc\.venv\lib\site-packages\flask\globals.py", line 47, in _find_app
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
to interface with the current application object in some way. To solve
this, set up an application context with app.app_context().  See the
documentation for more information.
```

**Comment by coleifer** [comment]
You can try just using the context manager - this app context must be some flask global hack.

```python
@huey.task()
def mail_tester(email):
    with app.app_context():
        ...
```

**Comment by amks1** [comment]
Yes, that's what I was afraid of. I guess Huey is not the right solution for my app then. 
Thanks and keep up the great work.
