### ISSUE TITLE
Restart automatically when disconnect with postgresql

### ISSUE THREAD

**Issue by Loches525** [coleifer/huey#619]
I am using SqlHuey and setup in supervisor with below setting. The disconnection error will always prompt when the database is closed, restart or the network is disconnected and every time need to manually restart huey. Please advise how to avoid it and restart huey automatically when this error happened.

> [program:huey]
command=huey_consumer app.tasks.huey -k thread -w 4
directory=/app
startsecs=0
stopwaitsecs=0
autostart=true
autorestart=true
stdout_logfile=/var/log/huey/huey.out
stderr_logfile=/var/log/huey/huey.err
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=100
stderr_logfile_maxbytes=50MB
stderr_logfile_backups=100

> Traceback (most recent call last):
  File "/Users/apple/Documents/code/projects/cms/.venv/lib/python3.7/site-packages/huey/consumer.py", line 159, in loop
    task_list = self.huey.read_schedule(now)
  File "/Users/apple/Documents/code/projects/cms/.venv/lib/python3.7/site-packages/huey/api.py", line 547, in read_schedule
    for task in self.storage.read_schedule(timestamp)]
  File "/Users/apple/Documents/code/projects/cms/.venv/lib/python3.7/site-packages/huey/contrib/sql_huey.py", line 139, in read_schedule
    return list(data)
  File "/Users/apple/Documents/code/projects/cms/.venv/lib/python3.7/site-packages/peewee.py", line 4175, in __exit__
    return self._helper.__exit__(exc_type, exc_val, exc_tb)
  File "/Users/apple/Documents/code/projects/cms/.venv/lib/python3.7/site-packages/peewee.py", line 4206, in __exit__
    self.rollback(False)
  File "/Users/apple/Documents/code/projects/cms/.venv/lib/python3.7/site-packages/peewee.py", line 4193, in rollback
    self.db.rollback()
  File "/Users/apple/Documents/code/projects/cms/.venv/lib/python3.7/site-packages/peewee.py", line 3301, in rollback
    return self._state.conn.rollback()
  File "/Users/apple/Documents/code/projects/cms/.venv/lib/python3.7/site-packages/peewee.py", line 2917, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/Users/apple/Documents/code/projects/cms/.venv/lib/python3.7/site-packages/peewee.py", line 190, in reraise
    raise value.with_traceback(tb)
  File "/Users/apple/Documents/code/projects/cms/.venv/lib/python3.7/site-packages/peewee.py", line 3301, in rollback
    return self._state.conn.rollback()
peewee.InterfaceError: connection already closed

**Comment by coleifer** [comment]
9b0ce1a9c63ffe8c8e51150cde81d068a7a7b088
