### ISSUE TITLE
Enqueueing periodic task error

### ISSUE THREAD

**Issue by vishwakarma0** [coleifer/huey#649]
Getting the below error very much frequently in all the periodic tasks. Earlier it used to work but it kind of stopped suddenly. Not sure why, could anyone suggest any changes or modifications that can be made?

```
[2022-01-11 14:35:25,320] INFO:huey.consumer.Scheduler:Scheduler:Enqueueing periodic task app.tasks.cleandb: e1371bd7-20d2-4ff3-8c05-6a0cbc374650.
[2022-01-11 14:35:25,322] ERROR:huey.consumer.Worker:Worker-1:Error reading from queue
Traceback (most recent call last):
  File "/home/ubuntu/sor_venv/lib/python3.8/site-packages/huey/consumer.py", line 94, in loop
    task = self.huey.dequeue()
  File "/home/ubuntu/sor_venv/lib/python3.8/site-packages/huey/api.py", line 287, in dequeue
    return self.deserialize_task(data)
  File "/home/ubuntu/sor_venv/lib/python3.8/site-packages/huey/api.py", line 263, in deserialize_task
    return self._registry.create_task(message)
  File "/home/ubuntu/sor_venv/lib/python3.8/site-packages/huey/registry.py", line 83, in create_task
    TaskClass = self.string_to_task(message.name)
  File "/home/ubuntu/sor_venv/lib/python3.8/site-packages/huey/registry.py", line 44, in string_to_task
    raise HueyException('%s not found in TaskRegistry' % task_str)
```

Thanks,
Vishwakarma

**Comment by coleifer** [comment]
https://huey.readthedocs.io/en/latest/troubleshooting.html
