### ISSUE TITLE
Problem with ForkingPickler, please help

### ISSUE THREAD

**Issue by VBobCat** [coleifer/huey#742]
I'm trying to integrate Huey with my Django application, but when trying to run the consumer, I get this error:

```
C:\Users\anton\django_backend\venv\Scripts\python.exe -m manage run_huey 
[2023-05-26 10:43:46,491] INFO:huey.consumer:23556:Huey consumer started with 4 process, PID 23556 at 2023-05-26 10:43:46.491088
[2023-05-26 10:43:46,491] INFO:huey.consumer:23556:Scheduler runs every 1 second(s).
[2023-05-26 10:43:46,491] INFO:huey.consumer:23556:Periodic tasks are enabled.
[2023-05-26 10:43:46,491] INFO:huey.consumer:23556:The following commands are available:
+ backend_main.tasks.task_mscloud_import_mail
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\anton\django_backend\manage.py", line 22, in <module>
    main()
  File "C:\Users\anton\django_backend\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\anton\django_backend\venv\Lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\Users\anton\django_backend\venv\Lib\site-packages\django\core\management\__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\anton\django_backend\venv\Lib\site-packages\django\core\management\base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\anton\django_backend\venv\Lib\site-packages\django\core\management\base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anton\django_backend\venv\Lib\site-packages\huey\contrib\djhuey\management\commands\run_huey.py", line 91, in handle
    consumer.run()
  File "C:\Users\anton\django_backend\venv\Lib\site-packages\huey\consumer.py", line 423, in run
    self.start()
  File "C:\Users\anton\django_backend\venv\Lib\site-packages\huey\consumer.py", line 391, in start
    self.scheduler.start()
  File "c:\Program Files\Python311\Lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "c:\Program Files\Python311\Lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Program Files\Python311\Lib\multiprocessing\context.py", line 336, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "c:\Program Files\Python311\Lib\multiprocessing\popen_spawn_win32.py", line 94, in __init__
    reduction.dump(process_obj, to_child)
  File "c:\Program Files\Python311\Lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'Consumer._create_process.<locals>._run'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\Program Files\Python311\Lib\multiprocessing\spawn.py", line 120, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Program Files\Python311\Lib\multiprocessing\spawn.py", line 130, in _main
    self = reduction.pickle.load(from_parent)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
EOFError: Ran out of input

Process finished with exit code 1
```

This is how Huey is configured in my `settings.py` (I tried to include anything that might be of interest):

```
"""
Django settings for backend project.
For more information on this file, see https://docs.djangoproject.com/en/4.2/topics/settings/
For the full list of settings and their values, see https://docs.djangoproject.com/en/4.2/ref/settings/
"""
# ...

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'dbbackup',
    'encrypted_model_fields',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'simple_history',
    'drf_spectacular',
    'drf_spectacular_sidecar',
    'huey.contrib.djhuey',  # <--------------------------- coleifer / huey
    'huey_django_orm',  # <--------------------------- avryhof / huey_django_orm
    'backend_main',
    'django_cleanup.apps.CleanupConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
]

# ...

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'OPTIONS': {
            'timeout': 500
        },
    }
}

# ...

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/
LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Sao_Paulo'
USE_I18N = True
USE_TZ = True
locale.setlocale(locale.LC_ALL, 'pt_BR.UTF-8')

# ...

# Settings for storages to be used with Django
# https://docs.djangoproject.com/en/4.2/ref/settings/#storages
STORAGES = {
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Settings for Django REST Framework
# https://www.django-rest-framework.org/api-guide/settings/
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_FILTER_BACKENDS': ['common.drf_utils.ModelFilterBackend'],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'PAGE_SIZE': 10,
}

# ...

# Settings for Huey
# https://huey.readthedocs.io/en/latest/contrib.html#django
HUEY = {
    'huey_class': 'huey_django_orm.storage.DjangoORMHuey',
    'utc': False,
    'immediate': False,
    'consumer': {
        'workers': 4,
        'worker_type': 'process',
    }
}

```

And this is my only task so far (at `backend_main\tasks.py`):

```
from huey import crontab
from huey.contrib.djhuey import db_periodic_task


@db_periodic_task(crontab(minute=0))
def task_mscloud_import_mail():
    from backend_mscloud.domain.import_mail import atualizar_graph_users
    atualizar_graph_users()
```

**Comment by coleifer** [comment]
Multiprocessing doesn't work well on windows. See

https://github.com/coleifer/huey/issues/551

You can try using threads or use wsl.

**Comment by VBobCat** [comment]
I see. For now, I'll put a platform-dependent choice between 'process' and 'threads' on settings.py and report here.
