### ISSUE TITLE
NoneType error when starting consumer with greenlet

### ISSUE THREAD

**Issue by sixhobbits** [coleifer/huey#759]
When starting a huey consumer with `-k greenlet` I get an error

```
(venv) hueysandbox$ huey_consumer.py app.huey -w 50 -k greenlet
```

```
Traceback (most recent call last):
  File "/Users/g/git/genai/hueysandbox/venv/bin/huey_consumer.py", line 61, in <module>
    consumer_main()
  File "/Users/g/git/genai/hueysandbox/venv/bin/huey_consumer.py", line 50, in consumer_main
    consumer = huey_instance.create_consumer(**config.values)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/g/git/genai/hueysandbox/venv/lib/python3.11/site-packages/huey/api.py", line 163, in create_consumer
    return Consumer(self, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/g/git/genai/hueysandbox/venv/lib/python3.11/site-packages/huey/consumer.py", line 295, in __init__
    self.stop_flag = self.environment.get_stop_flag()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/g/git/genai/hueysandbox/venv/lib/python3.11/site-packages/huey/consumer.py", line 210, in get_stop_flag
    return GreenEvent()
           ^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable
```

I'm using `huey==2.4.5` and `Python 3.11.4`. I see the error on both my M1 mac and X86 linux machines. 

In `app.py` I have the demo `add()` code from the quickstart guide. It works exactly as expected when not using `greenlet`.

**Comment by sixhobbits** [comment]
oh I fixed it with 

```
pip3 install gevent
```

after noticing this snippet in huey/consumer.py

```
try:
    import gevent
    from gevent import Greenlet
    from gevent.event import Event as GreenEvent
except ImportError:
    Greenlet = GreenEvent = None
```

leaving the issue open as I guess the missing dependency should be handled differently than throwing a TypeError - or at least the user should be prompted that gevent is missing first, but obviously feel free to close if you disagree
