### ISSUE TITLE
Lock Task ambiguous 

### ISSUE THREAD

**Issue by zN3utr4l** [coleifer/huey#763]
I'm looking for a replacement for Celery, which has minimal support on Windows as well.

### settings.py
```
# avryhof / huey_django_orm
INSTALLED_APPS.extend(['huey.contrib.djhuey', 'huey_django_orm'])

HUEY = {
    'huey_class': 'huey_django_orm.storage.DjangoORMHuey',
    'name': DATABASES['default']['NAME'],  # Use db name for huey.
    'results': True,  # Store return values of tasks.
    'store_none': False,  # If a task returns None, do not save to results.
    'immediate': DEBUG,  # If DEBUG=True, run synchronously.    (FALSE)
    'utc': True,  # Use UTC for all times internally.
    'compression': True, # Compress tasks and result data.
    'use_zlib': True, # Use zlib for compression instead of gzip.
    'consumer': {
        'workers': 4,
        'worker_type': 'thread',
        'initial_delay': 0.1,  # Smallest polling interval, same as -d.
        'backoff': 1,  # Exponential backoff using this rate, -b.
        'max_delay': 5,  # Max possible polling interval, -m.
        'scheduler_interval': 1,  # Check schedule every second, -s.
        'periodic': True,  # Enable crontab feature.
        'check_worker_health': True,  # Enable worker health checks.
        'health_check_interval': 1,  # Check worker health every second.
    },
}
```

### tasks.py
```
from test_app.models import Person
from datetime import datetime
from huey import crontab
from huey.contrib.djhuey import db_periodic_task, db_task, lock_task

@db_periodic_task(crontab())
@lock_task('create-lock')  # Goes *after* the task decorator.
def create():
    print(f"Executing create ...")
    name = datetime.now().strftime('%Y-%m-%d %H:%M')
    obj = Person.objects.create(name=name)

    # Generate database backup. Since this may take longer than an
    # hour, we want to ensure that it is not run concurrently.
    with lock_task('get-lock'):
        get(name)
    print(f"Finish create for object {obj.name} ...")

@db_task()
def get(name):
    print(f"Executing get ...")
    obj = Person.objects.get(name=name)
    print(f"Finish get for object {obj.name} ...")

@db_periodic_task(crontab())
@lock_task('count-lock')  # Goes *after* the task decorator.
def count():
    print(f"Executing count ...")
    objs = Person.objects.count()
    print(f"Finish count {objs} ...")
```

As soon as I ran `run_huey` it seems that each worker took the task to run it (on celery whoever arrived first ran it and the others waited for other tasks if I'm not mistaken).

![image](https://github.com/coleifer/huey/assets/73225008/9450bfab-3b39-43d0-b37f-3992cb0984ea)

It seems that `lock_task` didn't do its job or does the lock work for a single worker? if so, is there a way to make it work across multiple workers?

**!!! I don't know if this issue is linked to huey or huey_django_orm, if so I repost the same on huey_django_orm !!!**

### Traceback
```
[2023-09-07 11:10:56,883] ERROR:huey:Worker-3:Unhandled exception in task 7a1d373e-ff91-49e5-a4ac-c605966e999c.
Traceback (most recent call last):
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\huey\api.py", line 380, in _execute
    task_value = task.execute()
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\huey\api.py", line 792, in execute
    return func(*args, **kwargs)
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\huey\contrib\djhuey\__init__.py", line 135, in inner
    return fn(*args, **kwargs)
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\huey\api.py", line 881, in inner
    with self:
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\huey\api.py", line 886, in __enter__
    if not self._huey.put_if_empty(self._key, '1'):
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\huey\api.py", line 328, in put_if_empty
    return self.storage.put_if_empty(key, self.serializer.serialize(data))
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\huey_django_orm\storage.py", line 126, in put_if_empty
    if not self.has_data_for_key(key):
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\huey_django_orm\storage.py", line 123, in has_data_for_key
    return self.peek_data(key) != EmptyData
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\huey_django_orm\storage.py", line 103, in peek_data
    res = self.values.get(key=key)
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\django\db\models\query.py", line 439, in get
    raise self.model.MultipleObjectsReturned(
huey_django_orm.models.HueyKv.MultipleObjectsReturned: get() returned more than one HueyKv -- it returned 3!
[2023-09-07 11:10:56,884] ERROR:huey:Worker-1:Unhandled exception in task 7a1d373e-ff91-49e5-a4ac-c605966e999c.
Traceback (most recent call last):
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\huey\api.py", line 380, in _execute
    task_value = task.execute()
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\huey\api.py", line 792, in execute
    return func(*args, **kwargs)
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\huey\contrib\djhuey\__init__.py", line 135, in inner
    return fn(*args, **kwargs)
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\huey\api.py", line 881, in inner
    with self:
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\huey\api.py", line 886, in __enter__
    if not self._huey.put_if_empty(self._key, '1'):
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\huey\api.py", line 328, in put_if_empty
    return self.storage.put_if_empty(key, self.serializer.serialize(data))
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\huey_django_orm\storage.py", line 126, in put_if_empty
    if not self.has_data_for_key(key):
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\huey_django_orm\storage.py", line 123, in has_data_for_key
    return self.peek_data(key) != EmptyData
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\huey_django_orm\storage.py", line 103, in peek_data
    res = self.values.get(key=key)
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\django\db\models\query.py", line 439, in get
    raise self.model.MultipleObjectsReturned(
huey_django_orm.models.HueyKv.MultipleObjectsReturned: get() returned more than one HueyKv -- it returned 3!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\huey\api.py", line 382, in _execute
    self._tasks_in_flight.remove(task)
KeyError: test_app.tasks.create: 7a1d373e-ff91-49e5-a4ac-c605966e999c

[2023-09-07 11:10:56,902] ERROR:huey:Worker-2:Unhandled exception in task e2642e2e-8dbd-4001-99e1-e02ba6800d94.
Traceback (most recent call last):
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\huey\api.py", line 380, in _execute
    task_value = task.execute()
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\huey\api.py", line 792, in execute
    return func(*args, **kwargs)
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\huey\contrib\djhuey\__init__.py", line 135, in inner
    return fn(*args, **kwargs)
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\huey\api.py", line 882, in inner
    return fn(*args, **kwargs)
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\huey\api.py", line 890, in __exit__
    self._huey.delete(self._key)
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\huey\api.py", line 342, in delete
    return self.storage.delete_data(key)
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\huey\storage.py", line 188, in delete_data
    return self.pop_data(key) is not EmptyData
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\huey_django_orm\storage.py", line 112, in pop_data
    res = self.values.get(key=key)
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\django\db\models\query.py", line 439, in get
    raise self.model.MultipleObjectsReturned(
huey_django_orm.models.HueyKv.MultipleObjectsReturned: get() returned more than one HueyKv -- it returned 2!
[2023-09-07 11:10:56,903] ERROR:huey:Worker-4:Unhandled exception in task e2642e2e-8dbd-4001-99e1-e02ba6800d94.
Traceback (most recent call last):
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\huey\api.py", line 380, in _execute
    task_value = task.execute()
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\huey\api.py", line 792, in execute
    return func(*args, **kwargs)
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\huey\contrib\djhuey\__init__.py", line 135, in inner
    return fn(*args, **kwargs)
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\huey\api.py", line 882, in inner
    return fn(*args, **kwargs)
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\huey\api.py", line 890, in __exit__
    self._huey.delete(self._key)
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\huey\api.py", line 342, in delete
    return self.storage.delete_data(key)
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\huey\storage.py", line 188, in delete_data
    return self.pop_data(key) is not EmptyData
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\huey_django_orm\storage.py", line 112, in pop_data
    res = self.values.get(key=key)
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\django\db\models\query.py", line 439, in get
    raise self.model.MultipleObjectsReturned(
huey_django_orm.models.HueyKv.MultipleObjectsReturned: get() returned more than one HueyKv -- it returned 2!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\huey\api.py", line 382, in _execute
    self._tasks_in_flight.remove(task)
KeyError: test_app.tasks.count: e2642e2e-8dbd-4001-99e1-e02ba6800d94
```

**Comment by coleifer** [comment]
This looks like an issue with https://github.com/avryhof/huey_django_orm/ and not Huey. Apparently it is not properly taking tasks out of the queue. Try using one of the standard storage backends and reopen if you continue to see issues.
