### ISSUE TITLE
django.db.utils.OperationalError: server closed the connection unexpectedly

### ISSUE THREAD

**Issue by zN3utr4l** [coleifer/huey#764]
If I perform a sleep in any task (`db_*task`) if there is a request that goes to db this fails.
In this case it fails: `obj = Person.objects.create(name=name)`  `objs = Person.objects.count()`

I don't think this is due to django, because i tried to run the same tasks with django-q2, with the same sleep, and it doesn't skip the connection, the task runs all the way.

**After this error the tasks no longer start, below the error that is shown to the console**  (Traceback 2)

### settings.py
```
# avryhof / huey_django_orm
INSTALLED_APPS.extend(['huey.contrib.djhuey', 'huey_django_orm'])

HUEY = {
    'huey_class': 'huey_django_orm.storage.DjangoORMHuey',
    'name': DATABASES['default']['NAME'],  # Use db name for huey.
    'results': True,  # Store return values of tasks.
    'store_none': False,  # If a task returns None, do not save to results.
    'immediate': DEBUG,  # If DEBUG=True, run synchronously.
    'utc': True,  # Use UTC for all times internally.
    'compression': True,  # Compress tasks and result data.
    'use_zlib': True,  # Use zlib for compression instead of gzip.
    'consumer': {
        'workers': 1,
        'worker_type': 'thread',
        'initial_delay': 0.1,  # Smallest polling interval, same as -d.
        'backoff': 1,  # Exponential backoff using this rate, -b.
        'max_delay': 5,  # Max possible polling interval, -m.
        'scheduler_interval': 1,  # Check schedule every second, -s.
        'periodic': True,  # Enable crontab feature.
        'blocking': True,  # Use blocking list pop instead of polling Redis.
        'check_worker_health': True,  # Enable worker health checks.
        'health_check_interval': 1,  # Check worker health every second.
    },
}
```

### tasks.py
```
from time import sleep
from test_app.models import Person
from datetime import datetime
from huey import crontab
from huey.contrib.djhuey import db_periodic_task, db_task, lock_task


@db_periodic_task(crontab())
@lock_task('create-lock')  # Goes *after* the task decorator.
def create():
    print(f"Executing create ...")
    sleep(70)
    name = datetime.now().strftime('%Y-%m-%d %H:%M')
    obj = Person.objects.create(name=name)

    # Generate database backup. Since this may take longer than an
    # hour, we want to ensure that it is not run concurrently.
    with lock_task('get-lock'):
        get(name)
    print(f"Finish create for object {obj.name} ...")


@db_task()
def get(name):
    print(f"Executing get ...")
    obj = Person.objects.get(name=name)
    print(f"Finish get for object {obj.name} ...")


@db_periodic_task(crontab())
@lock_task('count-lock')  # Goes *after* the task decorator.
def count():
    sleep(70)
    print(f"Executing count ...")
    objs = Person.objects.count()
    print(f"Finish count {objs} ...")

```

### Traceback
```
(huey-example) (huey-example) PS D:\Repository\Analysis Detection\ReplaceCelery\huey_example> python manage.py run_huey
[2023-09-07 12:50:55,765] INFO:huey.consumer:MainThread:Huey consumer started with 1 thread, PID 6932 at 2023-09-07 10:50:55.765082
[2023-09-07 12:50:55,765] INFO:huey.consumer:MainThread:Scheduler runs every 1 second(s).
[2023-09-07 12:50:55,765] INFO:huey.consumer:MainThread:Periodic tasks are enabled.
[2023-09-07 12:50:55,765] INFO:huey.consumer:MainThread:The following commands are available:
+ test_app.tasks.create
+ test_app.tasks.get
+ test_app.tasks.count
[2023-09-07 12:50:55,843] INFO:huey.consumer.Scheduler:Scheduler:Enqueueing periodic task test_app.tasks.create: d1faa2bf-6d0c-40b2-a388-8a03be3b53bc.
[2023-09-07 12:50:55,856] INFO:huey.consumer.Scheduler:Scheduler:Enqueueing periodic task test_app.tasks.count: c814a288-bf01-4dc1-82f0-8af883a7e93f.
[2023-09-07 12:50:55,965] INFO:huey:Worker-1:Executing test_app.tasks.create: d1faa2bf-6d0c-40b2-a388-8a03be3b53bc
Executing create ...
[2023-09-07 12:51:55,791] INFO:huey.consumer.Scheduler:Scheduler:Enqueueing periodic task test_app.tasks.create: 93ebf5b0-2a0c-4c62-9870-0e916da12fba.
[2023-09-07 12:51:55,808] INFO:huey.consumer.Scheduler:Scheduler:Enqueueing periodic task test_app.tasks.count: e801970d-6dcf-496b-872e-589383470d4e.
[2023-09-07 12:52:06,035] ERROR:huey:Worker-1:Unhandled exception in task d1faa2bf-6d0c-40b2-a388-8a03be3b53bc.
Traceback (most recent call last):
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.OperationalError: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\huey\api.py", line 882, in inner
    return fn(*args, **kwargs)
  File "D:\Repository\Analysis Detection\ReplaceCelery\huey_example\test_app\tasks.py", line 14, in create
    obj = Person.objects.create(name=name)
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\django\db\models\manager.py", line 85, in manager_method       
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\django\db\models\query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\django\db\models\base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\django\db\models\base.py", line 776, in save_base
    updated = self._save_table(
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\django\db\models\base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\django\db\models\base.py", line 919, in _do_insert
    return manager._insert(
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\django\db\models\manager.py", line 85, in manager_method       
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\django\db\models\query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\django\db\models\sql\compiler.py", line 1416, in execute_sql   
    cursor.execute(sql, params)
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.OperationalError: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\django\db\backends\base\base.py", line 237, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\django\utils\asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\django\db\backends\postgresql\base.py", line 236, in create_cursor
    cursor = self.connection.cursor()
psycopg2.InterfaceError: connection already closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\huey\api.py", line 380, in _execute
    task_value = task.execute()
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\huey\api.py", line 792, in execute
    return func(*args, **kwargs)
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\huey\contrib\djhuey\__init__.py", line 135, in inner
    return fn(*args, **kwargs)
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\huey\api.py", line 882, in inner
    return fn(*args, **kwargs)
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\huey\api.py", line 890, in __exit__
    self._huey.delete(self._key)
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\huey\api.py", line 342, in delete
    return self.storage.delete_data(key)
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\huey\storage.py", line 188, in delete_data
    return self.pop_data(key) is not EmptyData
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\huey_django_orm\storage.py", line 112, in pop_data
    res = self.values.get(key=key)
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\django\db\models\query.py", line 431, in get
    num = len(clone)
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\django\db\models\query.py", line 262, in __len__
    self._fetch_all()
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\django\db\models\query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\django\db\models\query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\django\db\models\sql\compiler.py", line 1173, in execute_sql   
    cursor = self.connection.cursor()
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\django\utils\asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\django\db\backends\base\base.py", line 259, in cursor
    return self._cursor()
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\django\db\backends\base\base.py", line 237, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\django\db\backends\base\base.py", line 237, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\django\utils\asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "D:\Users\g.chirico\micromamba\envs\huey-example\lib\site-packages\django\db\backends\postgresql\base.py", line 236, in create_cursor
    cursor = self.connection.cursor()
django.db.utils.InterfaceError: connection already closed
```

### Traceback 2

```
[2023-09-07 12:53:16,348] INFO:huey:Worker-1:Executing test_app.tasks.create: 93ebf5b0-2a0c-4c62-9870-0e916da12fba
[2023-09-07 12:53:16,422] WARNING:huey:Worker-1:Task 93ebf5b0-2a0c-4c62-9870-0e916da12fba not run, unable to acquire lock.
[2023-09-07 12:53:16,487] INFO:huey:Worker-1:Executing test_app.tasks.count: e801970d-6dcf-496b-872e-589383470d4e
[2023-09-07 12:53:16,587] WARNING:huey:Worker-1:Task e801970d-6dcf-496b-872e-589383470d4e not run, unable to acquire lock.
[2023-09-07 12:53:16,699] INFO:huey:Worker-1:Executing test_app.tasks.create: 7ab5c7bc-d8ee-4d40-8d09-22ae67d480e2
[2023-09-07 12:53:16,765] WARNING:huey:Worker-1:Task 7ab5c7bc-d8ee-4d40-8d09-22ae67d480e2 not run, unable to acquire lock.
[2023-09-07 12:53:16,825] INFO:huey:Worker-1:Executing test_app.tasks.count: 1bcfe4b6-2f21-4850-b8b1-4ead7f06aad6
[2023-09-07 12:53:16,880] WARNING:huey:Worker-1:Task 1bcfe4b6-2f21-4850-b8b1-4ead7f06aad6 not run, unable to acquire lock.
[2023-09-07 12:53:55,792] INFO:huey.consumer.Scheduler:Scheduler:Enqueueing periodic task test_app.tasks.create: cd82d007-cf24-431a-95de-fc6cb94cb2f1.
[2023-09-07 12:53:55,808] INFO:huey.consumer.Scheduler:Scheduler:Enqueueing periodic task test_app.tasks.count: f4d1146e-c403-47d1-b252-1daa667d0b72.
[2023-09-07 12:53:55,875] INFO:huey:Worker-1:Executing test_app.tasks.create: cd82d007-cf24-431a-95de-fc6cb94cb2f1
[2023-09-07 12:53:55,991] WARNING:huey:Worker-1:Task cd82d007-cf24-431a-95de-fc6cb94cb2f1 not run, unable to acquire lock.
[2023-09-07 12:53:56,112] INFO:huey:Worker-1:Executing test_app.tasks.count: f4d1146e-c403-47d1-b252-1daa667d0b72
[2023-09-07 12:53:56,171] WARNING:huey:Worker-1:Task f4d1146e-c403-47d1-b252-1daa667d0b72 not run, unable to acquire lock.
[2023-09-07 12:54:55,769] INFO:huey.consumer.Scheduler:Scheduler:Enqueueing periodic task test_app.tasks.create: b6774689-90fc-4960-8344-dc9d3f712b9f.
[2023-09-07 12:54:55,784] INFO:huey.consumer.Scheduler:Scheduler:Enqueueing periodic task test_app.tasks.count: c87d323c-c3ec-49fd-89c2-6c100ec7d151.
[2023-09-07 12:54:55,816] INFO:huey:Worker-1:Executing test_app.tasks.create: b6774689-90fc-4960-8344-dc9d3f712b9f
[2023-09-07 12:54:55,898] WARNING:huey:Worker-1:Task b6774689-90fc-4960-8344-dc9d3f712b9f not run, unable to acquire lock.
[2023-09-07 12:54:56,008] INFO:huey:Worker-1:Executing test_app.tasks.count: c87d323c-c3ec-49fd-89c2-6c100ec7d151
[2023-09-07 12:54:56,070] WARNING:huey:Worker-1:Task c87d323c-c3ec-49fd-89c2-6c100ec7d151 not run, unable to acquire lock.
[2023-09-07 12:55:55,786] INFO:huey.consumer.Scheduler:Scheduler:Enqueueing periodic task test_app.tasks.create: 071535d4-3f0a-453e-903c-91218c6aad04.
```

**Comment by coleifer** [comment]
Server is terminating your connection, I don't think this is Huey related.
