### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'ssl'

### ISSUE THREAD

**Issue by stephenhutch** [coleifer/huey#777]
When creating a RedisHuey object:

    huey = RedisHuey(
        name='test',
        host='redis.example.com',
        port=6379,
        password="xxx",
        socket_timeout=5,
        username='default',
        ssl=True
    )

An error is raised:

    TypeError: __init__() got an unexpected keyword argument 'ssl'

Environment:

```
redis                       4.4.4   
huey                        2.5.0 
 
'redis_version': '6.2.6'
```

Connecting with the redis-py client works without error:

```
client = redis.Redis(
      host='redis.example.com',
      port=6379,
      password="xxx",
      socket_timeout=5,
      username='default',
      ssl=True
)
```

Full traceback:

```
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/redis/connection.py", line 1420, in get_connection
    connection = self._available_connections.pop()
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/huey/consumer.py", line 161, in loop
    task_list = self.huey.read_schedule(now)
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/huey/api.py", line 588, in read_schedule
    for task in self.storage.read_schedule(timestamp)]
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/huey/storage.py", line 448, in read_schedule
    tasks = self._pop(keys=[self.schedule_key], args=[unix_ts])
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/redis/commands/core.py", line 5794, in __call__
    return client.evalsha(self.sha, len(keys), *args)
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/redis/commands/core.py", line 5181, in evalsha
    return self._evalsha("EVALSHA", sha, numkeys, *keys_and_args)
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/redis/commands/core.py", line 5165, in _evalsha
    return self.execute_command(command, sha, numkeys, *keys_and_args)
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/redis/client.py", line 1255, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/redis/connection.py", line 1422, in get_connection
    connection = self.make_connection()
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/redis/connection.py", line 1462, in make_connection
    return self.connection_class(**self.connection_kwargs)
TypeError: __init__() got an unexpected keyword argument 'ssl'
ERROR:huey.consumer.Scheduler:Error reading schedule.
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/redis/connection.py", line 1420, in get_connection
    connection = self._available_connections.pop()
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/huey/consumer.py", line 161, in loop
    task_list = self.huey.read_schedule(now)
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/huey/api.py", line 588, in read_schedule
    for task in self.storage.read_schedule(timestamp)]
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/huey/storage.py", line 448, in read_schedule
    tasks = self._pop(keys=[self.schedule_key], args=[unix_ts])
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/redis/commands/core.py", line 5794, in __call__
    return client.evalsha(self.sha, len(keys), *args)
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/redis/commands/core.py", line 5181, in evalsha
    return self._evalsha("EVALSHA", sha, numkeys, *keys_and_args)
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/redis/commands/core.py", line 5165, in _evalsha
    return self.execute_command(command, sha, numkeys, *keys_and_args)
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/redis/client.py", line 1255, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/redis/connection.py", line 1422, in get_connection
    connection = self.make_connection()
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/redis/connection.py", line 1462, in make_connection
    return self.connection_class(**self.connection_kwargs)
TypeError: __init__() got an unexpected keyword argument 'ssl'
[2023-11-09 08:46:55,388] ERROR:huey.consumer.Scheduler:Scheduler:Error reading schedule.
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/redis/connection.py", line 1420, in get_connection
    connection = self._available_connections.pop()
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/huey/consumer.py", line 161, in loop
    task_list = self.huey.read_schedule(now)
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/huey/api.py", line 588, in read_schedule
    for task in self.storage.read_schedule(timestamp)]
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/huey/storage.py", line 448, in read_schedule
    tasks = self._pop(keys=[self.schedule_key], args=[unix_ts])
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/redis/commands/core.py", line 5794, in __call__
    return client.evalsha(self.sha, len(keys), *args)
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/redis/commands/core.py", line 5181, in evalsha
    return self._evalsha("EVALSHA", sha, numkeys, *keys_and_args)
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/redis/commands/core.py", line 5165, in _evalsha
    return self.execute_command(command, sha, numkeys, *keys_and_args)
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/redis/client.py", line 1255, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/redis/connection.py", line 1422, in get_connection
    connection = self.make_connection()
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/redis/connection.py", line 1462, in make_connection
    return self.connection_class(**self.connection_kwargs)
TypeError: __init__() got an unexpected keyword argument 'ssl'
ERROR:huey.consumer.Scheduler:Error reading schedule.
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/redis/connection.py", line 1420, in get_connection
    connection = self._available_connections.pop()
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/huey/consumer.py", line 161, in loop
    task_list = self.huey.read_schedule(now)
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/huey/api.py", line 588, in read_schedule
    for task in self.storage.read_schedule(timestamp)]
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/huey/storage.py", line 448, in read_schedule
    tasks = self._pop(keys=[self.schedule_key], args=[unix_ts])
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/redis/commands/core.py", line 5794, in __call__
    return client.evalsha(self.sha, len(keys), *args)
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/redis/commands/core.py", line 5181, in evalsha
    return self._evalsha("EVALSHA", sha, numkeys, *keys_and_args)
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/redis/commands/core.py", line 5165, in _evalsha
    return self.execute_command(command, sha, numkeys, *keys_and_args)
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/redis/client.py", line 1255, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/redis/connection.py", line 1422, in get_connection
    connection = self.make_connection()
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/redis/connection.py", line 1462, in make_connection
    return self.connection_class(**self.connection_kwargs)
TypeError: __init__() got an unexpected keyword argument 'ssl'
[2023-11-09 08:46:56,391] ERROR:huey.consumer.Scheduler:Scheduler:Error reading schedule.
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/redis/connection.py", line 1420, in get_connection
    connection = self._available_connections.pop()
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/huey/consumer.py", line 161, in loop
    task_list = self.huey.read_schedule(now)
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/huey/api.py", line 588, in read_schedule
    for task in self.storage.read_schedule(timestamp)]
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/huey/storage.py", line 448, in read_schedule
    tasks = self._pop(keys=[self.schedule_key], args=[unix_ts])
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/redis/commands/core.py", line 5794, in __call__
    return client.evalsha(self.sha, len(keys), *args)
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/redis/commands/core.py", line 5181, in evalsha
    return self._evalsha("EVALSHA", sha, numkeys, *keys_and_args)
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/redis/commands/core.py", line 5165, in _evalsha
    return self.execute_command(command, sha, numkeys, *keys_and_args)
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/redis/client.py", line 1255, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/redis/connection.py", line 1422, in get_connection
    connection = self.make_connection()
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/redis/connection.py", line 1462, in make_connection
    return self.connection_class(**self.connection_kwargs)
TypeError: __init__() got an unexpected keyword argument 'ssl'
ERROR:huey.consumer.Scheduler:Error reading schedule.
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/redis/connection.py", line 1420, in get_connection
    connection = self._available_connections.pop()
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/huey/consumer.py", line 161, in loop
    task_list = self.huey.read_schedule(now)
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/huey/api.py", line 588, in read_schedule
    for task in self.storage.read_schedule(timestamp)]
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/huey/storage.py", line 448, in read_schedule
    tasks = self._pop(keys=[self.schedule_key], args=[unix_ts])
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/redis/commands/core.py", line 5794, in __call__
    return client.evalsha(self.sha, len(keys), *args)
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/redis/commands/core.py", line 5181, in evalsha
    return self._evalsha("EVALSHA", sha, numkeys, *keys_and_args)
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/redis/commands/core.py", line 5165, in _evalsha
    return self.execute_command(command, sha, numkeys, *keys_and_args)
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/redis/client.py", line 1255, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/redis/connection.py", line 1422, in get_connection
    connection = self.make_connection()
  File "/home/ubuntu/.virtualenvs/huey-demo/lib/python3.7/site-packages/redis/connection.py", line 1462, in make_connection
    return self.connection_class(**self.connection_kwargs)
TypeError: __init__() got an unexpected keyword argument 'ssl'
```

Is there something wrong with the way the client is being used or with the library?

**Comment by stephenhutch** [comment]
It is pointing to redis instance with cluster mode enabled from what can be seen.

**Comment by coleifer** [comment]
I'd suggest raising this with the redis-py maintainers. You're supposed to be able to initialize a `ConnectionPool` with arguments that are then passed to the connections, but it looks like it isn't handling the `ssl` argument properly somehow. Here's an example you can share with them:

```python
from redis import *
r = Redis(ssl=True)  # OK

p = ConnectionPool(ssl=True)
r = Redis(connection_pool=p)  # Doesn't work.

p = ConnectionPool.from_url('rediss://')
r = Redis(connection_pool=p)  # Somehow this is OK, though?
```

In other words, I think `ConnectionPool` should handle the `ssl=` keyword argument, but for some reason it does not. However the `ConnectionPool` clearly supports specifying SSL because it accepts URLs using the `rediss://` protocol.

**Comment by andryyy** [comment]
Try `connection_class=redis.SSLConnection` as argument.

**Comment by coleifer** [comment]
Oh nice, thank you for jumping in @andryyy

**Comment by stephenhutch** [comment]
```
redis_connection_pool = redis.ConnectionPool(
    host='redis.example.com', port=6379, connection_class=redis.SSLConnection
)

huey = RedisHuey(
    name='test-ssl',
    connection_pool=redis_connection_pool
)
```
