### ISSUE TITLE
Python 3.4 + redi 2.10.3 - UnicodeDecodeError in test_queues

### ISSUE THREAD

**Issue by miohtama** [coleifer/huey#79]
Fresh git clone doesn't run tests cleanly on my Python 3.4 setup, `test_queues` UTF-8 errors give exception. Not sure if this is intentional, as there is clearly work done to have specific Python 3 support.

    ======================================================================
    ERROR: test_queues (huey.tests.backends.HueyBackendTestCase)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/Users/mikko/code/applebytestore/venv/src/huey/huey/api.py", line 152, in inner
        return fn(*args, **kwargs)
      File "/Users/mikko/code/applebytestore/venv/src/huey/huey/api.py", line 164, in _read
        return self.queue.read()
      File "/Users/mikko/code/applebytestore/venv/src/huey/huey/backends/redis_backend.py", line 39, in read
        return self.conn.rpop(self.queue_name)
      File "/Users/mikko/code/applebytestore/venv/lib/python3.4/site-packages/redis/client.py", line 1254, in rpop
        return self.execute_command('RPOP', name)
      File "/Users/mikko/code/applebytestore/venv/lib/python3.4/site-packages/redis/client.py", line 565, in execute_command
        return self.parse_response(connection, command_name, **options)
      File "/Users/mikko/code/applebytestore/venv/lib/python3.4/site-packages/redis/client.py", line 577, in parse_response
        response = connection.read_response()
      File "/Users/mikko/code/applebytestore/venv/lib/python3.4/site-packages/redis/connection.py", line 569, in read_response
        response = self._parser.read_response()
      File "/Users/mikko/code/applebytestore/venv/lib/python3.4/site-packages/redis/connection.py", line 266, in read_response
        response = response.decode(self.encoding)
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/Users/mikko/code/applebytestore/venv/src/huey/huey/tests/backends.py", line 85, in test_queues
        task = test_huey.dequeue()
      File "/Users/mikko/code/applebytestore/venv/src/huey/huey/api.py", line 210, in dequeue
        message = self._read()
      File "/Users/mikko/code/applebytestore/venv/src/huey/huey/api.py", line 154, in inner
        wrap_exception(exc_class)
      File "/Users/mikko/code/applebytestore/venv/src/huey/huey/utils.py", line 18, in wrap_exception
        raise exc_class(exc.message)
    AttributeError: 'UnicodeDecodeError' object has no attribute 'message'

    ----------------------------------------------------------------------

**Comment by coleifer** [comment]
Fixed.

**Comment by asihacker** [comment]
If your Redis configurations use {'decode_responses': True}, you can drop them and solve them!
