### ISSUE TITLE
Redis storage in blocking mode doesn't catch TimeoutError

### ISSUE THREAD

**Issue by lucacillario** [coleifer/huey#813]
**huey version:** 2.5.0
**redis-py version:** 4.0.2

I'm using RedisStorage in blocking mode, and the workers' log files are full of messages like this:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/huey/consumer.py", line 110, in loop
    task = self.huey.dequeue()
  File "/usr/local/lib/python3.8/site-packages/huey/api.py", line 317, in dequeue
    data = self.storage.dequeue()
  File "/usr/local/lib/python3.8/site-packages/huey/storage.py", line 421, in dequeue
    return self.conn.brpop(
  File "/usr/local/lib/python3.8/site-packages/redis/commands/core.py", line 2607, in brpop
    return self.execute_command("BRPOP", *keys)
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 548, in execute_command
    return conn.retry.call_with_retry(
  File "/usr/local/lib/python3.8/site-packages/redis/retry.py", line 65, in call_with_retry
    fail(error)
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 552, in <lambda>
    lambda error: self._disconnect_raise(conn, error),
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 538, in _disconnect_raise
    raise error
  File "/usr/local/lib/python3.8/site-packages/redis/retry.py", line 62, in call_with_retry
    return do()
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 549, in <lambda>
    lambda: self._send_command_parse_response(
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 525, in _send_command_parse_response
    return self.parse_response(conn, command_name, **options)
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 565, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.8/site-packages/redis/sentinel.py", line 68, in read_response
    return super().read_response(
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 512, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
  File "/usr/local/lib/python3.8/site-packages/redis/_parsers/resp2.py", line 15, in read_response
    result = self._read_response(disable_decoding=disable_decoding)
  File "/usr/local/lib/python3.8/site-packages/redis/_parsers/resp2.py", line 25, in _read_response
    raw = self._buffer.readline()
  File "/usr/local/lib/python3.8/site-packages/redis/_parsers/socket.py", line 115, in readline
    self._read_from_socket()
  File "/usr/local/lib/python3.8/site-packages/redis/_parsers/socket.py", line 78, in _read_from_socket
    raise TimeoutError("Timeout reading from socket")
redis.exceptions.TimeoutError: Timeout reading from socket
[2024-09-10 18:59:53,821] ERROR:huey.consumer.Worker:Worker-1:Error reading from queue
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/redis/_parsers/socket.py", line 65, in _read_from_socket
    data = self._sock.recv(socket_read_size)
socket.timeout: timed out
```

I'd add the Redis [TimeoutError](https://github.com/redis/redis-py/blob/master/redis/exceptions.py#L12) [here](https://github.com/coleifer/huey/blob/master/huey/storage.py#L423) and [here](https://github.com/coleifer/huey/blob/master/huey/storage.py#L577), so that it can be handled before the consumer logs the error. I'd be glad to open a PR :smile:

**Comment by coleifer** [comment]
Oh shit, I wonder if something changed recently, I'm not seeing that. What version of `redis-py` are you using?

Here is the example code:

```python
In [1]: from huey import *

In [2]: h = RedisHuey('test', blocking=True, read_timeout=3)                             

In [3]: h.storage.dequeue() is None  # This waits 3s then returns True
True
```

Output while monitoring Redis:

```
+1726243852.872159 [0 [::1]:35678] "BRPOP" "huey.redis.test" "3"
```

So, in short, I'm not seeing this. Are you calling `socket.settimeout` somewhere in your code?

**Comment by coleifer** [comment]
I've added a patch, but I'd like to have more info about how this is occurring. Please let me know.

**Comment by lucacillario** [comment]
@coleifer You're right, i wrote a custom Redis storage class to work with Redis Sentinel, and i'm pretty sure the timeout comes from Sentinel.

Tomorrow i'll investigate further. Let you know!

Thanks for the patch
